from os.path import basename, normpath

from supyr_struct.Test import Tag_Test_Library
from ..Field_Types import *
from .Defs.Objs.Tag import META_Tag


class Halo_Library(Tag_Test_Library):
    Default_Tag_Cls   = META_Tag
    Default_Defs_Path = "ReclaimerLib\\Halo\\META\\Defs\\"

    ID_Ext_Map = {'map':".map"
                  }

    Ext_ID_Map = {}

    for key in ID_Ext_Map.keys():
        Ext_ID_Map[ID_Ext_Map[key]] = key

    def __init__(self, *args, **kwargs):
        Tag_Test_Library.__init__(self, *args, **kwargs)

        #remove the autogenerated ID_Ext_Map to use the above one
        del self.__dict__['ID_Ext_Map']
