############# Credits and version info #############
# Definition autogenerated from Assembly XML tag def
#
# revision: 1		author: Assembly
# 	Generated plugin from scratch.
# revision: 2		author: DeadCanadian
# 	item types... for the ones i could figure out
# revision: 3		author: Lord Zedd
# 	h2 port
# revision: 4		author: Moses_of_Egypt
# 	Cleaned up and converted to SuPyr definition
#
####################################################
from reclaimer.common_descs import *
from supyr_struct.defs.tag_def import TagDef


_fx__additional_sound_input = Struct("additional_sound_input", 
    string_id_meta("dsp_effect"),
    rawdata_ref("low_frequency_sound_function"),
    Float("time_period"),
    ENDIAN=">", SIZE=28
    )


_fx__meta_def = BlockDef("_fx_", 
    BytesRaw("template_collection_block", SIZE=12, VISIBLE=False),
    SInt32("input_effect_name"),
    reflexive("additional_sound_inputs", _fx__additional_sound_input),
    TYPE=Struct, ENDIAN=">", SIZE=28
    )