############# Credits and version info #############
# Definition autogenerated from Assembly XML tag def
#
# revision: 1		author: Assembly
# 	Generated plugin from scratch.
# revision: 2		author: DeadCanadian
# 	named the tags and Verticies
# revision: 3		author: Lord Zedd
# 	port h2
# revision: 4		author: Moses_of_Egypt
# 	Cleaned up and converted to SuPyr definition
#
####################################################
from reclaimer.common_descs import *
from supyr_struct.defs.tag_def import TagDef


ant__vertice = Struct("vertice", 
    yp_float_rad("angle"),
    Float("length"),
    SInt16("sequence_index"),
    SInt16("unknown", VISIBLE=False),
    color_argb_float("color"),
    color_argb_float("lod_color"),
    Pad(16),
    ENDIAN=">", SIZE=64
    )


ant__meta_def = BlockDef("ant_", 
    string_id_meta("attachment_marker_name"),
    dependency("bitmaps"),
    dependency("physics"),
    BytesRaw("unknown", SIZE=28, VISIBLE=False),
    reflexive("vertices", ant__vertice),
    TYPE=Struct, ENDIAN=">", SIZE=76
    )