from reclaimer.common_descs import *
from supyr_struct.defs.tag_def import TagDef

bipd_ai_propertie_leap_jump_speed = (
    "none",
    "down",
    "step",
    "crouch",
    "stand",
    "storey",
    "tower",
    "infinite",
    )

bipd_ai_propertie_size = (
    "default",
    "tiny",
    "small",
    "medium",
    "large",
    "huge",
    "immobile",
    )

bipd_attachment_change_color = (
    "none",
    "primary",
    "secondary",
    "tertiary",
    "quaternary",
    )

bipd_constant_sound_volume = (
    "silent",
    "medium",
    "loud",
    "shout",
    "quiet",
    )

bipd_default_team = (
    "default",
    "player",
    "human",
    "covenant",
    "flood",
    "sentinel",
    "heretic",
    "prophet",
    "guilty",
    "unused9",
    "unused10",
    "unused11",
    "unused12",
    "unused13",
    "unused14",
    "unused15",
    )

bipd_grenade_type = (
    "human_fragmentation",
    "covenant_plasma",
    "brute_spike",
    "firebomb",
    )

bipd_item_scale = (
    "small",
    "medium",
    "large",
    "huge",
    )

bipd_lightmap_shadow_mode_size = (
    "default",
    "never",
    "always",
    "unknown",
    )

bipd_metagame_propertie_classification = (
    "infantry",
    "leader",
    "hero",
    "specialist",
    "light_vehicle",
    "heavy_vehicle",
    "giant_vehicle",
    "standard_vehicle",
    )

bipd_metagame_propertie_unit = (
    "brute",
    "grunt",
    "jackal",
    "marine",
    "bugger",
    "hunter",
    "flood_infection",
    "flood_carrier",
    "flood_combat",
    "flood_pureform",
    "sentinel",
    "elite",
    "turret",
    "mongoose",
    "warthog",
    "scorpion",
    "hornet",
    "pelican",
    "shade",
    "watchtower",
    "ghost",
    "chopper",
    "mauler",
    "wraith",
    "banshee",
    "phantom",
    "scarab",
    "guntower",
    )

bipd_motion_sensor_blip_size = (
    "medium",
    "small",
    "large",
    )

bipd_multiplayer_object_propertie_object_type = (
    "ordinary",
    "weapon",
    "grenade",
    "projectile",
    "powerup",
    "equipment",
    "light_land_vehicle",
    "heavy_land_vehicle",
    "flying_vehicle",
    "teleporter_2way",
    "teleporter_sender",
    "teleporter_receiver",
    "player_spawn_location",
    "player_respawn_zone",
    "hold_spawn_objective",
    "capture_spawn_objective",
    "hold_destination_objective",
    "capture_destination_objective",
    "hill_objective",
    "infection_haven_objective",
    "territory_objective",
    "vip_boundary_objective",
    "vip_destination_objective",
    "juggernaut_destination_objective",
    )

bipd_multiplayer_object_propertie_shape = (
    "none",
    "sphere",
    "cylinder",
    "box",
    )

bipd_multiplayer_object_propertie_spawn_timer_mode = (
    "on_death",
    "on_disturbance",
    )

bipd_object_type = (
    "biped",
    "vehicle",
    "weapon",
    "equipment",
    "terminal",
    "projectile",
    "scenery",
    "machine",
    "control",
    "sound_scenery",
    "crate",
    "creature",
    "giant",
    "effect_scenery",
    )

bipd_seat_ai_seat_type = (
    "none",
    "passenger",
    "gunner",
    "small_cargo",
    "large_cargo",
    "driver",
    )

bipd_sweetener_size = (
    "small",
    "medium",
    "large",
    )

bipd_water_density = (
    "default",
    "least",
    "some",
    "equal",
    "more",
    "more_still",
    "lots_more",
    )


bipd_early_mover_propertie = Struct("early_mover_properties",
    string_id_meta("name"),
    Pad(36),
    ENDIAN=">", SIZE=40
    )


bipd_ai_propertie = Struct("ai_properties",
    Bool32("flags",
        "destroyable_cover",
        "pathfinding_ignore_when_dead",
        "dynamic_cover",
        ),
    string_id_meta("ai_type_name"),
    Pad(4),
    SEnum16("size", *bipd_ai_propertie_size),
    SEnum16("leap_jump_speed", *bipd_ai_propertie_leap_jump_speed),
    ENDIAN=">", SIZE=16
    )


bipd_function = Struct("functions",
    Bool32("flags",
        "invert",
        "mapping_does_not_controls_active",
        "always_active",
        "random_time_offset",
        ),
    string_id_meta("import_name"),
    string_id_meta("export_name"),
    string_id_meta("turn_off_with"),
    Float("minimum_value"),
    rawdata_ref("default_function"),
    string_id_meta("scale_by"),
    ENDIAN=">", SIZE=44
    )


bipd_attachment = Struct("attachments",
    dependency("attachment"),
    string_id_meta("marker"),
    SEnum16("change_color", *bipd_attachment_change_color),
    SInt16("unknown"),
    string_id_meta("primary_scale"),
    string_id_meta("secondary_scale"),
    ENDIAN=">", SIZE=32
    )


bipd_widget = Struct("widgets",
    dependency("type"),
    ENDIAN=">", SIZE=16
    )


bipd_change_color_initial_permutation = Struct("initial_permutations",
    Pad(4),
    color_rgb_float("color_lower_bound"),
    color_rgb_float("color_upper_bound"),
    string_id_meta("variant_name"),
    ENDIAN=">", SIZE=32
    )


bipd_change_color_function = Struct("functions",
    Bool32("scale_flags",
        "blend_in_hsv",
        "more_colors",
        ),
    color_rgb_float("color_lower_bound"),
    color_rgb_float("color_upper_bound"),
    string_id_meta("darken_by"),
    string_id_meta("scale_by"),
    ENDIAN=">", SIZE=32
    )


bipd_change_color = Struct("change_colors",
    reflexive("initial_permutations", bipd_change_color_initial_permutation),
    reflexive("functions", bipd_change_color_function),
    ENDIAN=">", SIZE=24
    )


bipd_predicted_resource = Struct("predicted_resources",
    SInt16("type"),
    SInt16("resource_index"),
    UInt32("tag_index"),
    ENDIAN=">", SIZE=8
    )


bipd_multiplayer_object_propertie = Struct("multiplayer_object_properties",
    Bool16("engine_flags",
        "capture_the_flag",
        "slayer",
        "oddball",
        "king_of_the_hill",
        "juggernaut",
        "territories",
        "assault",
        "vip",
        "infection",
        ),
    SEnum8("object_type", *bipd_multiplayer_object_propertie_object_type),
    Bool8("teleporter_flags",
        "disallows_players",
        "allows_land_vehicles",
        "allows_heavy_vehicles",
        "allows_flying_vehicles",
        "allows_projectiles",
        ),
    Bool16("flags",
        "editor_only",
        ),
    SEnum8("shape", *bipd_multiplayer_object_propertie_shape),
    SEnum8("spawn_timer_mode", *bipd_multiplayer_object_propertie_spawn_timer_mode),
    SInt16("spawn_time"),
    SInt16("abandon_time"),
    Float("radius_width"),
    Float("length"),
    Float("top"),
    Float("bottom"),
    Float("unknown"),
    Float("unknown_1"),
    Float("unknown_2"),
    SInt32("unknown_3"),
    SInt32("unknown_4"),
    dependency("child_object"),
    SInt32("unknown_5"),
    dependency("shape_shader"),
    dependency("unknown_shader"),
    dependency("unknown_6"),
    dependency("unknown_7"),
    dependency("unknown_8"),
    dependency("unknown_9"),
    dependency("unknown_10"),
    dependency("unknown_11"),
    ENDIAN=">", SIZE=196
    )


bipd_metagame_propertie = Struct("metagame_properties",
    Bool8("flags",
        "must_have_active_seats",
        ),
    SEnum8("unit", *bipd_metagame_propertie_unit),
    SEnum8("classification", *bipd_metagame_propertie_classification),
    SInt8("unknown"),
    SInt16("points"),
    SInt16("unknown_1"),
    ENDIAN=">", SIZE=8
    )


bipd_camera_track = Struct("camera_tracks",
    dependency("track"),
    ENDIAN=">", SIZE=16
    )


bipd_unknown_7 = Struct("unknown_7",
    Float("unknown"),
    Float("unknown_1"),
    Float("unknown_2"),
    Float("unknown_3"),
    Float("unknown_4"),
    Float("unknown_5"),
    Float("unknown_6"),
    Float("unknown_7"),
    Float("unknown_8"),
    Float("unknown_9"),
    Float("unknown_10"),
    Float("unknown_11"),
    Float("unknown_12"),
    Float("unknown_13"),
    Float("unknown_14"),
    Float("unknown_15"),
    Float("unknown_16"),
    Float("unknown_17"),
    Float("unknown_18"),
    ENDIAN=">", SIZE=76
    )


bipd_posture = Struct("postures",
    string_id_meta("name"),
    Float("pill_offset_i"),
    Float("pill_offset_j"),
    Float("pill_offset_k"),
    ENDIAN=">", SIZE=16
    )


bipd_hud_interface = Struct("hud_interfaces",
    dependency("unit_hud_interface"),
    ENDIAN=">", SIZE=16
    )


bipd_dialogue_variant = Struct("dialogue_variants",
    SInt16("variant_number"),
    SInt16("unknown"),
    dependency("dialogue"),
    ENDIAN=">", SIZE=20
    )


bipd_powered_seat = Struct("powered_seats",
    Float("driver_powerup_time"),
    Float("driver_powerdown_time"),
    ENDIAN=">", SIZE=8
    )


bipd_weapon = Struct("weapons",
    dependency("weapon"),
    ENDIAN=">", SIZE=16
    )


bipd_seat_camera_track = Struct("camera_tracks",
    dependency("track"),
    ENDIAN=">", SIZE=16
    )


bipd_seat_unknown_6 = Struct("unknown_6",
    Float("unknown"),
    Float("unknown_1"),
    Float("unknown_2"),
    Float("unknown_3"),
    Float("unknown_4"),
    Float("unknown_5"),
    Float("unknown_6"),
    Float("unknown_7"),
    Float("unknown_8"),
    Float("unknown_9"),
    Float("unknown_10"),
    Float("unknown_11"),
    Float("unknown_12"),
    Float("unknown_13"),
    Float("unknown_14"),
    Float("unknown_15"),
    Float("unknown_16"),
    Float("unknown_17"),
    Float("unknown_18"),
    ENDIAN=">", SIZE=76
    )


bipd_seat_unit_hud_interface = Struct("unit_hud_interface",
    dependency("unit_hud_interface"),
    ENDIAN=">", SIZE=16
    )


bipd_seat = Struct("seats",
    Bool32("flags",
        "invisible",
        "locked",
        "driver",
        "gunner",
        "third_person_camera",
        "allows_weapons",
        "third_person_on_enter",
        "first_person_camera_slaved_to_gun",
        "allow_vehicle_communication_animations",
        "not_valid_without_driver",
        "allow_ai_noncombatants",
        "boarding_seat",
        "ai_firing_disabled_by_max_acceleration",
        "boarding_enters_seat",
        "boarding_need_any_passenger",
        "controls_open_and_close",
        "invalid_for_player",
        "invalid_for_non_player",
        "gunner_player_only",
        "invisible_under_major_damage",
        ("detachable_weapon", 1 << 22),
        ),
    string_id_meta("seat_animation"),
    string_id_meta("seat_marker_name"),
    string_id_meta("entry_marker_s_name"),
    string_id_meta("boarding_grenade_marker"),
    string_id_meta("boarding_grenade_string"),
    string_id_meta("boarding_melee_string"),
    string_id_meta("detach_weapon_string"),
    Float("ping_scale"),
    Float("turnover_time"),
    Float("acceleration_range_i"),
    Float("acceleration_range_j"),
    Float("acceleration_range_k"),
    Float("acceleration_action_scale"),
    Float("acceleration_attach_scale"),
    Float("ai_scariness"),
    SEnum16("ai_seat_type", *bipd_seat_ai_seat_type),
    SInt16("boarding_seat"),
    Float("listener_interpolation_factor"),
    Float("yaw_rate_bounds_min"),
    Float("yaw_rate_bounds_max"),
    Float("pitch_rate_bounds_min"),
    Float("pitch_rate_bounds_max"),
    Float("unknown"),
    Float("minimum_speed_reference"),
    Float("maximum_speed_reference"),
    Float("speed_exponent"),
    SInt16("unknown_1"),
    SInt16("unknown_2"),
    string_id_meta("camera_marker_name"),
    string_id_meta("camera_submerged_marker_name"),
    float_rad("pitch_auto_level"),
    float_rad("pitch_range_min"),
    float_rad("pitch_range_max"),
    reflexive("camera_tracks", bipd_seat_camera_track),
    float_rad("unknown_3"),
    float_rad("unknown_4"),
    float_rad("unknown_5"),
    reflexive("unknown_6", bipd_seat_unknown_6),
    reflexive("unit_hud_interface", bipd_seat_unit_hud_interface),
    string_id_meta("enter_seat_string"),
    float_rad("yaw_range_min"),
    float_rad("yaw_range_max"),
    dependency("built_in_gunner"),
    Float("entry_radius"),
    float_rad("entry_marker_cone_angle"),
    float_rad("entry_marker_facing_angle"),
    Float("maximum_relative_velocity"),
    string_id_meta("invisible_seat_region"),
    SInt32("runtime_invisible_seat_region_index"),
    ENDIAN=">", SIZE=228
    )


bipd_dead_sphere_shape = Struct("dead_sphere_shapes",
    string_id_meta("name"),
    SInt8("material_index"),
    SInt8("unknown"),
    SInt16("global_material_index"),
    Float("relative_mass_scale"),
    Float("friction"),
    Float("restitution"),
    Float("volume"),
    Float("mass"),
    SInt16("overall_shape_index"),
    SInt8("phantom_index"),
    SInt8("interaction_unknown"),
    SInt32("unknown_1"),
    SInt16("size"),
    SInt16("size_1"),
    SInt32("offset"),
    SInt32("unknown_2"),
    Float("radius"),
    Pad(12),
    SInt32("unknown_4"),
    SInt16("size_2"),
    SInt16("size_3"),
    SInt32("offset_1"),
    SInt32("unknown_5"),
    Float("radius_1"),
    Pad(12),
    Float("translation_i"),
    Float("translation_j"),
    Float("translation_k"),
    Float("translation_radius"),
    ENDIAN=">", SIZE=112
    )


bipd_pill_shape = Struct("pill_shapes",
    string_id_meta("name"),
    SInt8("material_index"),
    SInt8("unknown"),
    SInt16("global_material_index"),
    Float("relative_mass_scale"),
    Float("friction"),
    Float("restitution"),
    Float("volume"),
    Float("mass"),
    SInt16("overall_shape_index"),
    SInt8("phantom_index"),
    SInt8("interaction_unknown"),
    SInt32("unknown_1"),
    SInt16("size"),
    SInt16("size_1"),
    SInt32("offset"),
    SInt32("unknown_2"),
    Float("radius"),
    Pad(12),
    Float("bottom_i"),
    Float("bottom_j"),
    Float("bottom_k"),
    Float("bottom_radius"),
    Float("top_i"),
    Float("top_j"),
    Float("top_k"),
    Float("top_radius"),
    ENDIAN=">", SIZE=96
    )


bipd_sphere_shape = Struct("sphere_shapes",
    string_id_meta("name"),
    SInt8("material_index"),
    SInt8("unknown"),
    SInt16("global_material_index"),
    Float("relative_mass_scale"),
    Float("friction"),
    Float("restitution"),
    Float("volume"),
    Float("mass"),
    SInt16("overall_shape_index"),
    SInt8("phantom_index"),
    SInt8("interaction_unknown"),
    SInt32("unknown_1"),
    SInt16("size"),
    SInt16("size_1"),
    SInt32("offset"),
    SInt32("unknown_2"),
    Float("radius"),
    Pad(12),
    SInt32("unknown_4"),
    SInt16("size_2"),
    SInt16("size_3"),
    SInt32("offset_1"),
    SInt32("unknown_5"),
    Float("radius_1"),
    Pad(12),
    Float("translation_i"),
    Float("translation_j"),
    Float("translation_k"),
    Float("translation_radius"),
    ENDIAN=">", SIZE=112
    )


bipd_contact_point = Struct("contact_points",
    string_id_meta("marker_name"),
    ENDIAN=">", SIZE=4
    )


bipd_meta_def = BlockDef("bipd",
    SEnum16("object_type", *bipd_object_type),
    Bool16("flags",
        "does_not_cast_shadow",
        "search_cardinal_direction_lightmaps",
        ("not_a_pathfinding_obstacle", 1 << 3),
        "extension_of_parent",
        "does_not_cause_collision_damage",
        "early_mover",
        "early_mover_localized_physics",
        "use_static_massive_lightmap_sample",
        "object_scales_attachments",
        "inherits_player_s_appearance",
        "dead_bipeds_can_t_localize",
        "attach_to_clusters_by_dynamic_sphere",
        "effects_created_by_this_object_do_not_spawn_objects_in_multiplayer",
        ),
    Float("bounding_radius"),
    Float("bounding_offset_x"),
    Float("bounding_offset_y"),
    Float("bounding_offset_z"),
    Float("acceleration_scale"),
    SEnum16("lightmap_shadow_mode_size", *bipd_lightmap_shadow_mode_size),
    SEnum8("sweetener_size", *bipd_sweetener_size),
    SEnum8("water_density", *bipd_water_density),
    SInt32("unknown"),
    Float("dynamic_light_sphere_radius"),
    Float("dynamic_light_sphere_offset_x"),
    Float("dynamic_light_sphere_offset_y"),
    Float("dynamic_light_sphere_offset_z"),
    string_id_meta("default_model_variant"),
    dependency("model"),
    dependency("crate_object"),
    dependency("collision_damage"),
    reflexive("early_mover_properties", bipd_early_mover_propertie),
    dependency("creation_effect"),
    dependency("material_effects"),
    dependency("melee_impact"),
    reflexive("ai_properties", bipd_ai_propertie),
    reflexive("functions", bipd_function),
    SInt16("hud_text_message_index"),
    SInt16("unknown_1"),
    reflexive("attachments", bipd_attachment),
    reflexive("widgets", bipd_widget),
    reflexive("change_colors", bipd_change_color),
    reflexive("predicted_resources", bipd_predicted_resource),
    reflexive("multiplayer_object_properties", bipd_multiplayer_object_propertie),
    Bool32("flags_1",
        "circular_aiming",
        "destroyed_after_dying",
        "half_speed_interpolation",
        "fires_from_camera",
        "entrance_inside_bounding_sphere",
        "doesn_t_show_readied_weapon",
        "causes_passenger_dialogue",
        "resists_pings",
        "melee_attack_is_fatal",
        "don_t_reface_during_pings",
        "has_no_aiming",
        "simple_creature",
        "impact_melee_attaches_to_unit",
        "impact_melee_dies_on_shield",
        "cannot_open_doors_automatically",
        "melee_attackers_cannot_attach",
        "not_instantly_killed_by_melee",
        "shield_sapping",
        "runs_around_flaming",
        "inconsequential",
        "special_cinematic_unit",
        "ignored_by_autoaiming",
        "shields_fry_infection_forms",
        "can_dual_wield",
        ("acts_as_gunner_for_parent", 1 << 25),
        "controlled_by_parent_gunner",
        "parent_s_primary_weapon",
        "unit_has_boost",
        ),
    SEnum16("default_team", *bipd_default_team),
    SEnum16("constant_sound_volume", *bipd_constant_sound_volume),
    reflexive("metagame_properties", bipd_metagame_propertie),
    dependency("integrated_light_toggle"),
    float_rad("camera_field_of_view"),
    Float("camera_stiffness"),
    SInt16("unknown_2"),
    SInt16("unknown_3"),
    string_id_meta("camera_marker_name"),
    string_id_meta("camera_submerged_marker_name"),
    float_rad("pitch_auto_level"),
    float_rad("pitch_range_min"),
    float_rad("pitch_range_max"),
    reflexive("camera_tracks", bipd_camera_track),
    float_rad("unknown_4"),
    float_rad("unknown_5"),
    float_rad("unknown_6"),
    reflexive("unknown_7", bipd_unknown_7),
    Float("acceleration_range_i"),
    Float("acceleration_range_j"),
    Float("acceleration_range_k"),
    Float("acceleration_action_scale"),
    Float("acceleration_attach_scale"),
    Float("soft_ping_threshold"),
    Float("soft_ping_interrupt_time"),
    Float("hard_ping_threshold"),
    Float("hard_ping_interrupt_time"),
    Float("feign_death_threshold"),
    Float("feign_death_time"),
    Float("distance_of_evade_animation"),
    Float("distance_of_dive_animation"),
    Float("stunned_movement_threshold"),
    Float("feign_death_chance"),
    Float("feign_repeat_chance"),
    dependency("spawned_turret_character"),
    SInt16("spawned_actor_count_min"),
    SInt16("spawned_actor_count_max"),
    Float("spawned_velocity"),
    float_rad("aiming_velocity_maximum"),
    float_rad("aiming_acceleration_maximum"),
    Float("casual_aiming_modifier"),
    float_rad("looking_velocity_maximum"),
    float_rad("looking_acceleration_maximum"),
    string_id_meta("right_hand_node"),
    string_id_meta("left_hand_node"),
    string_id_meta("preferred_gun_node"),
    dependency("melee_damage"),
    dependency("boarding_melee_damage"),
    dependency("boarding_melee_response"),
    dependency("ejection_melee_damage"),
    dependency("ejection_melee_response"),
    dependency("landing_melee_damage"),
    dependency("flurry_melee_damage"),
    dependency("obstacle_smash_damage"),
    SEnum16("motion_sensor_blip_size", *bipd_motion_sensor_blip_size),
    SEnum16("item_scale", *bipd_item_scale),
    reflexive("postures", bipd_posture),
    reflexive("hud_interfaces", bipd_hud_interface),
    reflexive("dialogue_variants", bipd_dialogue_variant),
    Float("grenade_velocity"),
    SEnum16("grenade_type", *bipd_grenade_type),
    SInt16("grenade_count"),
    reflexive("powered_seats", bipd_powered_seat),
    reflexive("weapons", bipd_weapon),
    reflexive("seats", bipd_seat),
    Float("emp_radius"),
    dependency("emp_effect"),
    dependency("boost_collision_damage"),
    Float("boost_peak_power"),
    Float("boost_rise_power"),
    Float("boost_peak_time"),
    Float("boost_fall_power"),
    Float("boost_dead_time"),
    Float("lipsync_attack_weight"),
    Float("lipsync_decay_weight"),
    dependency("detach_damage"),
    dependency("detached_weapon"),
    float_rad("moving_turning_speed"),
    Bool32("flags_2",
        "turns_without_animating",
        "passes_through_other_bipeds",
        "immune_to_falling_damage",
        "rotate_while_airborne",
        "use_limp_body_physics",
        ("random_speed_increase", 1 << 6),
        ("spawn_death_children_on_destroy", 1 << 8),
        "stunned_by_emp_damage",
        "dead_physics_when_stunned",
        "always_ragdoll_when_dead",
        ),
    float_rad("stationary_turning_threshold"),
    Float("jump_velocity"),
    Float("maximum_soft_landing_time"),
    Float("maximum_hard_landing_time"),
    Float("minimum_soft_landing_velocity"),
    Float("minimum_hard_landing_velocity"),
    Float("maximum_hard_landing_velocity"),
    Float("death_hard_landing_velocity"),
    Float("stun_duration"),
    Float("standing_camera_height"),
    Float("crouching_camera_height"),
    Float("crouch_transition_time"),
    float_rad("camera_interpolation_start"),
    float_rad("camera_interpolation_end"),
    Float("camera_forward_movement_scale"),
    Float("camera_side_movement_scale"),
    Float("camera_vertical_movement_scale"),
    Float("camera_exclusion_distance"),
    Float("autoaim_width"),
    Bool32("lock_on_flags",
        "locked_by_human_targeting",
        "locked_by_plasma_targeting",
        "always_locked_by_human_targeting",
        ),
    Float("lock_on_distance"),
    SInt16("physics_control_node_index"),
    SInt16("unknown_8"),
    Float("unknown_9"),
    Float("unknown_10"),
    SInt16("pelvis_node_index"),
    SInt16("head_node_index"),
    Float("headshot_acceleration_scale"),
    dependency("area_damage_effect"),
    Bool32("flags_3",
        "centered_at_origin",
        "shape_spherical",
        "use_player_physics",
        "climb_any_surface",
        "flying",
        "not_physical",
        "dead_character_collision_group",
        ("never_rests", 1 << 8),
        ),
    Float("height_standing"),
    Float("height_crouching"),
    Float("radius"),
    Float("mass"),
    string_id_meta("living_material_name"),
    string_id_meta("dead_material_name"),
    SInt16("living_global_material_index"),
    SInt16("dead_global_material_index"),
    reflexive("dead_sphere_shapes", bipd_dead_sphere_shape),
    reflexive("pill_shapes", bipd_pill_shape),
    reflexive("sphere_shapes", bipd_sphere_shape),
    float_rad("maximum_slope_angle"),
    float_rad("downhill_falloff_angle"),
    float_rad("downhill_cutoff_angle"),
    float_rad("uphill_falloff_angle"),
    float_rad("uphill_cutoff_angle"),
    Float("downhill_velocity_scale"),
    Float("uphill_velocity_scale"),
    Float("unknown_11"),
    Float("unknown_12"),
    Float("unknown_13"),
    Float("unknown_14"),
    Float("unknown_15"),
    Float("unknown_16"),
    Float("unknown_17"),
    Float("falling_velocity_scale"),
    Float("unknown_18"),
    float_rad("bank_angle"),
    Float("bank_apply_time"),
    Float("bank_decay_time"),
    Float("pitch_ratio"),
    Float("maximum_velocity"),
    Float("maximum_sidestep_velocity"),
    Float("acceleration"),
    Float("deceleration"),
    float_rad("angular_velocity_maximum"),
    float_rad("angular_acceleration_maximum"),
    Float("crouch_velocity_modifier"),
    Pad(4),
    reflexive("contact_points", bipd_contact_point),
    dependency("reanimation_character"),
    dependency("transformation_muffin"),
    dependency("death_spawn_character"),
    SInt16("death_spawn_count"),
    SInt16("unknown_20"),
    Pad(4),
    Float("unknown_22"),
    Float("unknown_23"),
    Float("unknown_24"),
    Float("unknown_25"),
    float_rad("unknown_26"),
    float_rad("unknown_27"),
    Pad(8),
    Float("unknown_29"),
    Float("unknown_30"),
    Float("unknown_31"),
    Float("unknown_32"),
    Float("unknown_33"),
    Float("unknown_34"),
    Float("unknown_35"),
    Float("unknown_36"),
    float_rad("unknown_37"),
    float_rad("unknown_38"),
    Float("unknown_39"),
    Float("unknown_40"),
    Float("unknown_41"),
    Float("unknown_42"),
    Float("unknown_43"),
    TYPE=Struct, ENDIAN=">", SIZE=1248
    )