############# Credits and version info #############
# Definition autogenerated from Assembly XML tag def
#
# revision: 1		author: Assembly
# 	Generated plugin from scratch.
# revision: 2		author: DarkShallFall-
# 	Labeled some reflexives and acouple values(Sep 26 2008)
# revision: 3		author: OrangeMohawk
# 	Position, Rotation, Scaling, Flashing/Fading, Bitmap Skewing.
# revision: 4		author: Lord Zedd
# 	Updated some things
# revision: 5		author: Moses_of_Egypt
# 	Cleaned up and converted to SuPyr definition
#
####################################################
from reclaimer.common_descs import *
from supyr_struct.defs.tag_def import TagDef


chad_position_animation = Struct("animation", 
    SInt32("frame_number"),
    QStruct("position", INCLUDE=xyz_float),
    ENDIAN=">", SIZE=16
    )


chad_position = Struct("position", 
    reflexive("animation", chad_position_animation),
    rawdata_ref("function"),
    ENDIAN=">", SIZE=32
    )


chad_rotation_animation = Struct("animation", 
    SInt32("frame_number"),
    ypr_float_rad("angle"),
    ENDIAN=">", SIZE=16
    )


chad_rotation = Struct("rotation", 
    reflexive("animation", chad_rotation_animation),
    rawdata_ref("function"),
    ENDIAN=">", SIZE=32
    )


chad_size_animation = Struct("animation", 
    SInt32("frame_number"),
    QStruct("stretch", INCLUDE=xy_float),
    ENDIAN=">", SIZE=12
    )


chad_size = Struct("size", 
    reflexive("animation", chad_size_animation),
    rawdata_ref("unknown", VISIBLE=False),
    ENDIAN=">", SIZE=32
    )


chad_color_animation = Struct("animation", 
    SInt32("frame_number"),
    BytesRaw("unknown", SIZE=4, VISIBLE=False),
    ENDIAN=">", SIZE=8
    )


chad_color = Struct("color", 
    reflexive("animation", chad_color_animation),
    rawdata_ref("function"),
    ENDIAN=">", SIZE=32
    )


chad_alpha_animation = Struct("animation", 
    SInt32("frame_number"),
    Float("alpha"),
    ENDIAN=">", SIZE=8
    )


chad_alpha = Struct("alpha", 
    reflexive("animation", chad_alpha_animation),
    rawdata_ref("function"),
    ENDIAN=">", SIZE=32
    )


chad_alpha_unknown_animation = Struct("animation", 
    SInt32("frame_number"),
    Float("alpha"),
    ENDIAN=">", SIZE=8
    )


chad_alpha_unknown = Struct("alpha_unknown", 
    reflexive("animation", chad_alpha_unknown_animation),
    rawdata_ref("function"),
    ENDIAN=">", SIZE=32
    )


chad_bitmap_animation = Struct("animation", 
    SInt32("frame_number"),
    QStruct("movement_1", INCLUDE=xy_float),
    QStruct("movement_2", INCLUDE=xy_float),
    ENDIAN=">", SIZE=20
    )


chad_bitmap = Struct("bitmap", 
    reflexive("animation", chad_bitmap_animation),
    rawdata_ref("function"),
    ENDIAN=">", SIZE=32
    )


chad_meta_def = BlockDef("chad", 
    Bool16("flags", 
        ("loops", 1 << 1),
        ),
    SInt16("unknown", VISIBLE=False),
    reflexive("position", chad_position),
    reflexive("rotation", chad_rotation),
    reflexive("size", chad_size),
    reflexive("color", chad_color),
    reflexive("alpha", chad_alpha),
    reflexive("alpha_unknown", chad_alpha_unknown),
    reflexive("bitmap", chad_bitmap),
    SInt32("number_of_frames", VISIBLE=False),
    TYPE=Struct, ENDIAN=">", SIZE=92
    )