############# Credits and version info #############
# Definition autogenerated from Assembly XML tag def
#
# revision: 1		author: Assembly
# 	Generated plugin from scratch.
# revision: 2		author: Moses_of_Egypt
# 	Cleaned up and converted to SuPyr definition
#
####################################################
from reclaimer.common_descs import *
from supyr_struct.defs.tag_def import TagDef


cisc_puppet_unknown_2 = Struct("unknown_2", 
    BytesRaw("unknown_0", SIZE=40, VISIBLE=False),
    dependency("unknown_1", VISIBLE=False),
    VISIBLE=False,
    ENDIAN=">", SIZE=56
    )


cisc_puppet = Struct("puppet", 
    ascii_str32("import_name"),
    string_id_meta("name"),
    string_id_meta("variant"),
    dependency("puppet_animation"),
    dependency("puppet_object"),
    BytesRaw("unknown_0", SIZE=4, VISIBLE=False),
    Array("unknown_array", SUB_STRUCT=SInt8("unknown"), SIZE=4, VISIBLE=False),
    SInt32("unknown_1", VISIBLE=False),
    rawdata_ref("import_script"),
    reflexive("unknown_2", cisc_puppet_unknown_2),
    ENDIAN=">", SIZE=116
    )


cisc_shot_lighting = Struct("lighting", 
    dependency("cinematic_light"),
    SInt32("owner_puppet_index"),
    string_id_meta("marker"),
    ENDIAN=">", SIZE=24
    )


cisc_shot_unknown_3_unknown_1 = Struct("unknown_1", 
    BytesRaw("unknown", SIZE=4, VISIBLE=False),
    VISIBLE=False,
    ENDIAN=">", SIZE=4
    )


cisc_shot_unknown_3 = Struct("unknown_3", 
    BytesRaw("unknown_0", SIZE=32, VISIBLE=False),
    reflexive("unknown_1", cisc_shot_unknown_3_unknown_1),
    VISIBLE=False,
    ENDIAN=">", SIZE=44
    )


cisc_shot_sound = Struct("sound", 
    dependency("sound"),
    SInt32("frame"),
    Float("unknown_0", VISIBLE=False),
    string_id_meta("unknown_1"),
    BytesRaw("unknown_2", SIZE=4, VISIBLE=False),
    string_id_meta("unknown_3"),
    ENDIAN=">", SIZE=36
    )


cisc_shot_background_sound = Struct("background_sound", 
    BytesRaw("unknown", SIZE=4, VISIBLE=False),
    dependency("sound"),
    SInt32("frame"),
    ENDIAN=">", SIZE=24
    )


cisc_shot_effect = Struct("effect", 
    dependency("effect"),
    SInt32("frame"),
    string_id_meta("marker"),
    SInt32("owner_puppet_index"),
    ENDIAN=">", SIZE=28
    )


cisc_shot_function_value = Struct("value", 
    BytesRaw("unknown_0", SIZE=4, VISIBLE=False),
    SInt32("unknown_1", VISIBLE=False),
    Float("unknown_2", VISIBLE=False),
    Float("unknown_3", VISIBLE=False),
    VISIBLE=False,
    ENDIAN=">", SIZE=16
    )


cisc_shot_function = Struct("function", 
    SInt32("owner_puppet_index"),
    string_id_meta("target_function_name"),
    reflexive("values", cisc_shot_function_value),
    ENDIAN=">", SIZE=20
    )


cisc_shot_cortana_effect = Struct("cortana_effect", 
    dependency("effect"),
    BytesRaw("unknown", SIZE=4, VISIBLE=False),
    ENDIAN=">", SIZE=20
    )


cisc_shot_import_script = Struct("import_script", 
    SInt32("frame"),
    rawdata_ref("import_script"),
    ENDIAN=">", SIZE=24
    )


cisc_shot_frame = Struct("frame", 
    QStruct("position", INCLUDE=xyz_float),
    Array("unknown_array", SUB_STRUCT=Float("unknown"), SIZE=8, VISIBLE=False),
    Float("fov"),
    Bool32("flags", 
        "enable_depth_of_field",
        ),
    Float("near_plane"),
    Float("far_plane"),
    Float("focal_depth"),
    Float("blur_amount"),
    ENDIAN=">", SIZE=68
    )


cisc_shot = Struct("shot", 
    rawdata_ref("opening_import_script"),
    SInt32("unknown_0", VISIBLE=False),
    BytesRaw("unknown_1", SIZE=4, VISIBLE=False),
    Float("unknown_2", VISIBLE=False),
    reflexive("lighting", cisc_shot_lighting),
    reflexive("unknown_3", cisc_shot_unknown_3),
    reflexive("sounds", cisc_shot_sound),
    reflexive("background_sounds", cisc_shot_background_sound),
    reflexive("effects", cisc_shot_effect),
    reflexive("functions", cisc_shot_function),
    reflexive("cortana_effects", cisc_shot_cortana_effect),
    reflexive("import_scripts", cisc_shot_import_script),
    rawdata_ref("import_script"),
    SInt32("loaded_frame_count"),
    reflexive("frames", cisc_shot_frame),
    ENDIAN=">", SIZE=164
    )


cisc_texture_camera_shot_frame = Struct("frame", 
    SInt32("unknown", VISIBLE=False),
    QStruct("position", INCLUDE=xyz_float),
    Array("unknown_array", SUB_STRUCT=Float("unknown"), SIZE=8, VISIBLE=False),
    Float("fov"),
    Bool32("flags", 
        "enable_depth_of_field",
        ),
    Float("near_plane"),
    Float("far_plane"),
    Float("focal_depth"),
    Float("blur_amount"),
    ENDIAN=">", SIZE=72
    )


cisc_texture_camera_shot = Struct("shot", 
    reflexive("frames", cisc_texture_camera_shot_frame),
    ENDIAN=">", SIZE=12
    )


cisc_texture_camera = Struct("texture_camera", 
    string_id_meta("name"),
    string_id_meta("unknown"),
    reflexive("shots", cisc_texture_camera_shot),
    ENDIAN=">", SIZE=20
    )


cisc_meta_def = BlockDef("cisc", 
    string_id_meta("name"),
    ascii_str32("anchor_name"),
    BytesRaw("unknown_0", SIZE=4, VISIBLE=False),
    rawdata_ref("import_script_0"),
    reflexive("puppets", cisc_puppet),
    reflexive("shots", cisc_shot),
    reflexive("texture_cameras", cisc_texture_camera),
    rawdata_ref("import_script_1"),
    BytesRaw("unknown_1", SIZE=4, VISIBLE=False),
    TYPE=Struct, ENDIAN=">", SIZE=120
    )