############# Credits and version info #############
# Definition autogenerated from Assembly XML tag def
#
# revision: 1		author: Assembly
# 	Generated plugin from scratch.
# revision: 2		author: DarkShallFall
# 	Labeled most of the tag
# revision: 3		author: DarkShallFall
# 	H2
# revision: 4		author: Moses_of_Egypt
# 	Cleaned up and converted to SuPyr definition
#
####################################################
from reclaimer.common_descs import *
from supyr_struct.defs.tag_def import TagDef

clwd_integration_type = (
    "verlet",
    )


clwd_vertice = Struct("vertice", 
    QStruct("initial_position", INCLUDE=xyz_float),
    QStruct("uv", INCLUDE=ij_float),
    ENDIAN=">", SIZE=20
    )


clwd_indice = Struct("indice", 
    SInt16("idx"),
    ENDIAN=">", SIZE=2
    )


clwd_link = Struct("link", 
    SInt16("index_1"),
    SInt16("index_2"),
    Float("default_distance"),
    ENDIAN=">", SIZE=8
    )


clwd_meta_def = BlockDef("clwd", 
    Bool32("flags", 
        "doesn_t_use_wind",
        "uses_grid_attach_top",
        ),
    string_id_meta("marker_attachment_name"),
    string_id_meta("second_marker_attachment_name"),
    dependency("shader"),
    SInt16("grid_x_dimension"),
    SInt16("grid_y_dimension"),
    QStruct("grid_spacing", INCLUDE=xy_float),
    BytesRaw("unknown_0", SIZE=12, VISIBLE=False),
    SEnum16("integration_type", *clwd_integration_type),
    SInt16("number_iterations"),
    Float("weight"),
    Float("drag"),
    Float("wind_scale"),
    Float("wind_flappiness_scale"),
    Float("longest_rod"),
    BytesRaw("unknown_1", SIZE=24, VISIBLE=False),
    reflexive("vertices", clwd_vertice),
    reflexive("indices", clwd_indice),
    BytesRaw("unknown_2", SIZE=12, VISIBLE=False),
    reflexive("links", clwd_link),
    TYPE=Struct, ENDIAN=">", SIZE=148
    )