############# Credits and version info #############
# Definition autogenerated from Assembly XML tag def
#
# revision: 1		author: -DeToX-
# 	Created layout of plugin
# revision: 2		author: Moses_of_Egypt
# 	Cleaned up and converted to SuPyr definition
#
####################################################
from reclaimer.common_descs import *
from supyr_struct.defs.tag_def import TagDef


draw_meta_def = BlockDef("draw", 
    BytesRaw("unknown", SIZE=4, VISIBLE=False),
    TYPE=Struct, ENDIAN=">", SIZE=4
    )