############# Credits and version info #############
# Definition autogenerated from Assembly XML tag def
#
# revision: 1		author: Assembly
# 	Generated plugin from scratch.
# revision: 2		author: Deadcanadian
# 	naming stuff
# revision: 3		author: OrangeMohawk
# 	Data types
# revision: 4		author: Moses_of_Egypt
# 	Cleaned up and converted to SuPyr definition
#
####################################################
from reclaimer.common_descs import *
from supyr_struct.defs.tag_def import TagDef


dsrc_data_integer_value = Struct("integer_value", 
    string_id_meta("data_type"),
    SInt32("value"),
    ENDIAN=">", SIZE=8
    )


dsrc_data_string_value = Struct("string_value", 
    string_id_meta("data_type"),
    StrLatin1("value", SIZE=20),
    ENDIAN=">", SIZE=36
    )


dsrc_data_stringid_value = Struct("stringid_value", 
    string_id_meta("data_type"),
    string_id_meta("value"),
    ENDIAN=">", SIZE=8
    )


dsrc_data = Struct("data", 
    reflexive("integer_values", dsrc_data_integer_value),
    reflexive("string_values", dsrc_data_string_value),
    reflexive("stringid_values", dsrc_data_stringid_value),
    string_id_meta("unknown"),
    ENDIAN=">", SIZE=40
    )


dsrc_meta_def = BlockDef("dsrc", 
    string_id_meta("name"),
    BytesRaw("unknown", SIZE=12, VISIBLE=False),
    reflexive("data", dsrc_data),
    TYPE=Struct, ENDIAN=">", SIZE=28
    )