from reclaimer.common_descs import *
from supyr_struct.defs.tag_def import TagDef

effe_event_part_camera_mode = (
    "independent_of_camera_mode",
    "first_person_only",
    "third_person_only",
    "both_first_and_third",
    )

effe_event_part_create_in_disposition = (
    "either_mode",
    "violent_mode_only",
    "nonviolent_mode_only",
    )

effe_event_part_create_in_environment = (
    "any_environment",
    "air_only",
    "water_only",
    "space_only",
    )

effe_event_particle_system_coordinate_system = (
    "world",
    "local",
    "parent",
    )

effe_event_particle_system_emitter_output_kind = (
    "none",
    "plus",
    "times",
    )


effe_location = Struct("locations",
    string_id_meta("marker_name"),
    SInt32("unknown"),
    SInt8("unknown_1"),
    SInt8("unknown_2"),
    SInt8("unknown_3"),
    SInt8("unknown_4"),
    ENDIAN=">", SIZE=12
    )


effe_event_part = Struct("parts",
    SEnum16("create_in_environment", *effe_event_part_create_in_environment),
    SEnum16("create_in_disposition", *effe_event_part_create_in_disposition),
    SInt16("location_index"),
    SInt16("unknown"),
    SInt16("unknown_1"),
    SInt8("unknown_2"),
    SEnum8("camera_mode", *effe_event_part_camera_mode),
    StrLatin1("anticipated_tag_class", SIZE=4),
    dependency("spawned_tag"),
    Float("velocity_bounds_min"),
    Float("velocity_bounds_max"),
    Pad(8),
    float_rad("velocity_cone_angle"),
    float_rad("angular_velocity_bounds_min"),
    float_rad("angular_velocity_bounds_max"),
    Float("radius_modifier_bounds_min"),
    Float("radius_modifier_bounds_max"),
    Float("origin_offset_x"),
    Float("origin_offset_y"),
    Float("origin_offset_z"),
    float_rad("origin_rotation_i"),
    float_rad("origin_rotation_j"),
    Bool32("a_scales_values",
        ),
    Bool32("b_scales_values",
        ),
    ENDIAN=">", SIZE=96
    )


effe_event_acceleration = Struct("accelerations",
    SEnum16("create_in_environment", *effe_event_part_create_in_environment),
    SEnum16("create_in_disposition", *effe_event_part_create_in_disposition),
    SInt16("location_index"),
    SInt16("unknown"),
    Float("acceleration"),
    Float("inner_cone_angle"),
    Float("outer_cone_angle"),
    ENDIAN=">", SIZE=20
    )


effe_event_particle_system_emitter_unknown_25_unknown_1 = Struct("unknown_1",
    Pad(4),
    SInt8("input"),
    SInt8("input_range"),
    SEnum8("output_kind", *effe_event_particle_system_emitter_output_kind),
    SInt8("output"),
    rawdata_ref("unknown_1"),
    Pad(8),
    ENDIAN=">", SIZE=36
    )


effe_event_particle_system_emitter_unknown_25 = Struct("unknown_25",
    Pad(4),
    reflexive("unknown_1", effe_event_particle_system_emitter_unknown_25_unknown_1),
    Pad(8),
    ENDIAN=">", SIZE=24
    )


effe_event_particle_system_emitter_unknown_43 = Struct("unknown_43",
    Float("unknown"),
    Float("unknown_1"),
    Float("unknown_2"),
    Float("unknown_3"),
    ENDIAN=">", SIZE=16
    )


effe_event_particle_system_emitter_compiled_function = Struct("compiled_functions",
    Float("unknown"),
    Float("unknown_1"),
    Float("unknown_2"),
    Float("unknown_3"),
    Float("unknown_4"),
    Float("unknown_5"),
    Float("unknown_6"),
    Float("unknown_7"),
    Float("unknown_8"),
    Float("unknown_9"),
    Float("unknown_10"),
    Float("unknown_11"),
    Float("unknown_12"),
    Float("unknown_13"),
    Float("unknown_14"),
    Float("unknown_15"),
    ENDIAN=">", SIZE=64
    )


effe_event_particle_system_emitter_compiled_color_function = Struct("compiled_color_functions",
    Float("red"),
    Float("green"),
    Float("blue"),
    Float("magnitude"),
    ENDIAN=">", SIZE=16
    )


effe_event_particle_system_emitter = Struct("emitters",
    string_id_meta("name"),
    Bool16("unknown",
        ),
    SInt16("unknown_1"),
    Pad(16),
    SInt8("input"),
    SInt8("input_range"),
    SEnum8("output_kind", *effe_event_particle_system_emitter_output_kind),
    SInt8("output"),
    rawdata_ref("unknown_3"),
    Pad(32),
    SInt8("input_1"),
    SInt8("input_range_1"),
    SEnum8("output_kind_1", *effe_event_particle_system_emitter_output_kind),
    SInt8("output_1"),
    rawdata_ref("unknown_5"),
    Pad(32),
    SInt8("input_2"),
    SInt8("input_range_2"),
    SEnum8("output_kind_2", *effe_event_particle_system_emitter_output_kind),
    SInt8("output_2"),
    rawdata_ref("unknown_7"),
    Pad(8),
    SInt8("input_3"),
    SInt8("input_range_3"),
    SEnum8("output_kind_3", *effe_event_particle_system_emitter_output_kind),
    SInt8("output_3"),
    rawdata_ref("unknown_9"),
    Pad(8),
    SInt8("input_4"),
    SInt8("input_range_4"),
    SEnum8("output_kind_4", *effe_event_particle_system_emitter_output_kind),
    SInt8("output_4"),
    rawdata_ref("unknown_11"),
    Pad(8),
    SInt8("input_5"),
    SInt8("input_range_5"),
    SEnum8("output_kind_5", *effe_event_particle_system_emitter_output_kind),
    SInt8("output_5"),
    rawdata_ref("unknown_13"),
    Pad(8),
    SInt8("input_6"),
    SInt8("input_range_6"),
    SEnum8("output_kind_6", *effe_event_particle_system_emitter_output_kind),
    SInt8("output_6"),
    rawdata_ref("unknown_15"),
    Pad(8),
    SInt8("input_7"),
    SInt8("input_range_7"),
    SEnum8("output_kind_7", *effe_event_particle_system_emitter_output_kind),
    SInt8("output_7"),
    rawdata_ref("unknown_17"),
    Pad(8),
    SInt8("input_8"),
    SInt8("input_range_8"),
    SEnum8("output_kind_8", *effe_event_particle_system_emitter_output_kind),
    SInt8("output_8"),
    rawdata_ref("unknown_19"),
    Pad(8),
    dependency("particle_physics"),
    SInt8("unknown_21"),
    SInt8("unknown_22"),
    SInt8("unknown_23"),
    SInt8("unknown_24"),
    reflexive("unknown_25", effe_event_particle_system_emitter_unknown_25),
    SInt8("input_9"),
    SInt8("input_range_9"),
    SEnum8("output_kind_9", *effe_event_particle_system_emitter_output_kind),
    SInt8("output_9"),
    rawdata_ref("unknown_26"),
    Pad(32),
    SInt8("input_10"),
    SInt8("input_range_10"),
    SEnum8("output_kind_10", *effe_event_particle_system_emitter_output_kind),
    SInt8("output_10"),
    rawdata_ref("unknown_28"),
    Pad(8),
    SInt8("input_11"),
    SInt8("input_range_11"),
    SEnum8("output_kind_11", *effe_event_particle_system_emitter_output_kind),
    SInt8("output_11"),
    rawdata_ref("unknown_30"),
    Pad(8),
    SInt8("input_12"),
    SInt8("input_range_12"),
    SEnum8("output_kind_12", *effe_event_particle_system_emitter_output_kind),
    SInt8("output_12"),
    rawdata_ref("unknown_32"),
    Pad(8),
    SInt8("input_13"),
    SInt8("input_range_13"),
    SEnum8("output_kind_13", *effe_event_particle_system_emitter_output_kind),
    SInt8("output_13"),
    rawdata_ref("unknown_34"),
    Pad(8),
    SInt8("input_14"),
    SInt8("input_range_14"),
    SEnum8("output_kind_14", *effe_event_particle_system_emitter_output_kind),
    SInt8("output_14"),
    rawdata_ref("particle_scale"),
    Pad(8),
    SInt8("input_15"),
    SInt8("input_range_15"),
    SEnum8("output_kind_15", *effe_event_particle_system_emitter_output_kind),
    SInt8("output_15"),
    rawdata_ref("particle_tint"),
    Pad(8),
    SInt8("input_16"),
    SInt8("input_range_16"),
    SEnum8("output_kind_16", *effe_event_particle_system_emitter_output_kind),
    SInt8("output_16"),
    rawdata_ref("particle_alpha"),
    Pad(8),
    SInt8("input_17"),
    SInt8("input_range_17"),
    SEnum8("output_kind_17", *effe_event_particle_system_emitter_output_kind),
    SInt8("output_17"),
    rawdata_ref("particle_alpha_black_point"),
    Pad(8),
    SInt32("unknown_40"),
    SInt32("unknown_41"),
    SInt32("unknown_42"),
    reflexive("unknown_43", effe_event_particle_system_emitter_unknown_43),
    reflexive("compiled_functions", effe_event_particle_system_emitter_compiled_function),
    reflexive("compiled_color_functions", effe_event_particle_system_emitter_compiled_color_function),
    ENDIAN=">", SIZE=752
    )


effe_event_particle_system = Struct("particle_systems",
    SInt8("unknown"),
    SInt8("unknown_1"),
    SInt8("unknown_2"),
    SInt8("unknown_3"),
    dependency("particle"),
    SInt16("unknown_4"),
    SInt16("location_index"),
    SEnum16("coordinate_system", *effe_event_particle_system_coordinate_system),
    SEnum16("environment", *effe_event_part_create_in_environment),
    SEnum16("disposition", *effe_event_part_create_in_disposition),
    SEnum16("camera_mode", *effe_event_part_camera_mode),
    SInt16("sort_bias"),
    Bool16("flags",
        ),
    Float("unknown_5"),
    Float("unknown_6"),
    Float("unknown_7"),
    Float("unknown_8"),
    Pad(4),
    Float("unknown_10"),
    Float("amount_size"),
    Float("unknown_11"),
    Float("lod_in_distance"),
    Float("lod_feather_in_delta"),
    reflexive("emitters", effe_event_particle_system_emitter),
    Float("unknown_12"),
    ENDIAN=">", SIZE=92
    )


effe_event = Struct("events",
    string_id_meta("name"),
    SInt32("unknown"),
    SInt8("unknown_1"),
    SInt8("unknown_2"),
    SInt8("unknown_3"),
    SInt8("unknown_4"),
    Float("skip_fraction"),
    Float("delay_bounds_min"),
    Float("delay_bounds_max"),
    Float("duration_bounds_min"),
    Float("duration_bounds_max"),
    reflexive("parts", effe_event_part),
    reflexive("accelerations", effe_event_acceleration),
    reflexive("particle_systems", effe_event_particle_system),
    ENDIAN=">", SIZE=68
    )


effe_unknown_13 = Struct("unknown_13",
    Pad(12),
    ENDIAN=">", SIZE=12
    )


effe_meta_def = BlockDef("effe",
    Bool32("flags",
        ("dark_casings", 1 << 10),
        ),
    SInt32("unknown"),
    Float("unknown_1"),
    Pad(4),
    Float("unknown_3"),
    SInt8("unknown_4"),
    SInt8("unknown_5"),
    SInt8("unknown_6"),
    SInt8("unknown_7"),
    SInt16("loop_start_event"),
    SInt16("unknown_8"),
    Pad(4),
    reflexive("locations", effe_location),
    reflexive("events", effe_event),
    dependency("looping_sound"),
    SInt8("location_index"),
    SInt8("event_index"),
    SInt16("unknown_10"),
    Float("always_play_distance"),
    Float("never_play_distance"),
    Float("unknown_11"),
    Float("unknown_12"),
    reflexive("unknown_13", effe_unknown_13),
    TYPE=Struct, ENDIAN=">", SIZE=104
    )