############# Credits and version info #############
# Definition autogenerated from Assembly XML tag def
#
# revision: 1		author: Assembly
# 	Generated plugin from scratch.
# revision: 2		author: Moses_of_Egypt
# 	Cleaned up and converted to SuPyr definition
#
####################################################
from reclaimer.common_descs import *
from supyr_struct.defs.tag_def import TagDef


glvs_unknown_0_unknown_unknown_0_unknown_1 = Struct("unknown_1", 
    UInt32("unknown", VISIBLE=False),
    VISIBLE=False,
    ENDIAN=">", SIZE=4
    )


glvs_unknown_0_unknown_unknown_0 = Struct("unknown_0", 
    UInt32("unknown_0", VISIBLE=False),
    reflexive("unknown_1", glvs_unknown_0_unknown_unknown_0_unknown_1),
    VISIBLE=False,
    ENDIAN=">", SIZE=16
    )


glvs_unknown_0_unknown = Struct("unknown", 
    reflexive("unknown_0", glvs_unknown_0_unknown_unknown_0),
    BytesRaw("unknown_1", SIZE=4, VISIBLE=False),
    VISIBLE=False,
    ENDIAN=">", SIZE=16
    )


glvs_unknown_0 = Struct("unknown_0", 
    reflexive("unknown", glvs_unknown_0_unknown),
    VISIBLE=False,
    ENDIAN=">", SIZE=12
    )


glvs_vertex_shader_unknown_2 = Struct("unknown_2", 
    string_id_meta("unknown_0", VISIBLE=False),
    BytesRaw("unknown_1", SIZE=4, VISIBLE=False),
    VISIBLE=False,
    ENDIAN=">", SIZE=8
    )


glvs_vertex_shader = Struct("vertex_shader", 
    rawdata_ref("unknown_0", VISIBLE=False),
    rawdata_ref("unknown_1", VISIBLE=False),
    reflexive("unknown_2", glvs_vertex_shader_unknown_2),
    BytesRaw("unknown_3", SIZE=24, VISIBLE=False),
    UInt32("vertex_shader"),
    ENDIAN=">", SIZE=80
    )


glvs_meta_def = BlockDef("glvs", 
    reflexive("unknown_0", glvs_unknown_0),
    BytesRaw("unknown_1", SIZE=4, VISIBLE=False),
    reflexive("vertex_shaders", glvs_vertex_shader),
    TYPE=Struct, ENDIAN=">", SIZE=28
    )