from reclaimer.common_descs import *
from supyr_struct.defs.tag_def import TagDef

hlmt_model_object_data_type = (
    "not_set",
    "user_defined",
    "auto_generated",
    )

hlmt_new_damage_info_collision_damage_reporting_type = (
    "guardians",
    "falling_damage",
    "collision",
    "melee",
    "explosion",
    "magnum",
    "plasma_pistol",
    "needler",
    "mauler",
    "smg",
    "plasma_rifle",
    "battle_rifle",
    "carbine",
    "shotgun",
    "sniper_rifle",
    "beam_rifle",
    "assault_rifle",
    "spiker",
    "fuel_rod_cannon",
    "missile_pod",
    "rocket_launcher",
    "spartan_laser",
    "brute_shot",
    "flamethrower",
    "sentinel_gun",
    "energy_sword",
    "gravity_hammer",
    "frag_grenade",
    "plasma_grenade",
    "spike_grenade",
    "firebomb_grenade",
    "flag",
    "bomb",
    "bomb_explosion",
    "ball",
    "machinegun_turret",
    "plasma_cannon",
    "plasma_mortar",
    "plasma_turret",
    "banshee",
    "ghost",
    "mongoose",
    "scorpion",
    "scorpion_gunner",
    "spectre",
    "spectre_gunner",
    "warthog",
    "warthog_gunner",
    "warthog_gauss_turret",
    "wraith",
    "wraith_gunner",
    "tank",
    "chopper",
    "hornet",
    "mantis",
    "prowler",
    "sentinel_beam",
    "sentinel_rpg",
    "teleporter",
    "tripmine",
    "elephant_turret",
    )

hlmt_new_damage_info_damage_constraint_type = (
    "hinge",
    "limited_hinge",
    "ragdoll",
    "stiff_spring",
    "ball_and_socket",
    "prismatic",
    )

hlmt_new_damage_info_damage_section_instant_response_constraint_damage_type = (
    "none",
    "destroy_one_of_group",
    "destroy_entire_group",
    "loosen_one_of_group",
    "loosen_entire_group",
    )

hlmt_new_damage_info_damage_section_instant_response_response_type = (
    "recieves_all_damage",
    "recieves_area_effect_damage",
    "recieves_local_damage",
    )

hlmt_new_damage_info_damage_section_instant_response_unknown_special_damage = (
    "none",
    "_1",
    "_2",
    "_3",
    )

hlmt_variant_region_permutation_state_state = (
    "default",
    "minor_damage",
    "medium_damage",
    "major_damage",
    "destroyed",
    )

hlmt_variant_region_sort_order = (
    "no_sorting",
    "neg_5_closest",
    "neg_4",
    "neg_3",
    "neg_2",
    "neg_1",
    "_0_same_as_model",
    "_1",
    "_2",
    "_3",
    "_4",
    "_5_farthest",
    )


hlmt_variant_region_permutation_state = Struct("states",
    string_id_meta("name"),
    SInt8("model_permutation_index"),
    Bool8("property_flags",
        "blurred",
        "hella_blurred",
        "shielded",
        ),
    SEnum16("state", *hlmt_variant_region_permutation_state_state),
    dependency("looping_effect"),
    string_id_meta("looping_effect_marker_name"),
    Float("initial_probability"),
    ENDIAN=">", SIZE=32
    )


hlmt_variant_region_permutation = Struct("permutations",
    string_id_meta("name"),
    SInt8("model_permutation_index"),
    Bool8("flags",
        "copy_states_to_all_permutations",
        ),
    SInt8("unknown"),
    SInt8("unknown_1"),
    Float("probability"),
    reflexive("states", hlmt_variant_region_permutation_state),
    Pad(12),
    ENDIAN=">", SIZE=36
    )


hlmt_variant_region = Struct("regions",
    string_id_meta("name"),
    SInt8("model_region_index"),
    SInt8("unknown"),
    SInt16("parent_variant_index"),
    reflexive("permutations", hlmt_variant_region_permutation),
    SEnum32("sort_order", *hlmt_variant_region_sort_order),
    ENDIAN=">", SIZE=24
    )


hlmt_variant_object = Struct("objects",
    string_id_meta("parent_marker"),
    string_id_meta("child_marker"),
    string_id_meta("child_variant"),
    dependency("child_object"),
    ENDIAN=">", SIZE=28
    )


hlmt_variant = Struct("variants",
    string_id_meta("name"),
    SInt8("model_region_0_index"),
    SInt8("model_region_1_index"),
    SInt8("model_region_2_index"),
    SInt8("model_region_3_index"),
    SInt8("model_region_4_index"),
    SInt8("model_region_5_index"),
    SInt8("model_region_6_index"),
    SInt8("model_region_7_index"),
    SInt8("model_region_8_index"),
    SInt8("model_region_9_index"),
    SInt8("model_region_10_index"),
    SInt8("model_region_11_index"),
    SInt8("model_region_12_index"),
    SInt8("model_region_13_index"),
    SInt8("model_region_14_index"),
    SInt8("model_region_15_index"),
    reflexive("regions", hlmt_variant_region),
    reflexive("objects", hlmt_variant_object),
    SInt32("instance_group_index"),
    Pad(8),
    ENDIAN=">", SIZE=56
    )


hlmt_instance_group_instance_member = Struct("instance_members",
    SInt32("unknown"),
    string_id_meta("instance_name"),
    Float("probability"),
    Bool32("instance_flags_1",
        "instance_0",
        "instance_1",
        "instance_2",
        "instance_3",
        "instance_4",
        "instance_5",
        "instance_6",
        "instance_7",
        "instance_8",
        "instance_9",
        "instance_10",
        "instance_11",
        "instance_12",
        "instance_13",
        "instance_14",
        "instance_15",
        "instance_16",
        "instance_17",
        "instance_18",
        "instance_19",
        "instance_20",
        "instance_21",
        "instance_22",
        "instance_23",
        "instance_24",
        "instance_25",
        "instance_26",
        "instance_27",
        "instance_28",
        "instance_29",
        "instance_30",
        "instance_31",
        ),
    Bool32("instance_flags_2",
        "instance_32",
        "instance_33",
        "instance_34",
        "instance_35",
        "instance_36",
        "instance_37",
        "instance_38",
        "instance_39",
        "instance_40",
        "instance_41",
        "instance_42",
        "instance_43",
        "instance_44",
        "instance_45",
        "instance_46",
        "instance_47",
        "instance_48",
        "instance_49",
        "instance_50",
        "instance_51",
        "instance_52",
        "instance_53",
        "instance_54",
        "instance_55",
        "instance_56",
        "instance_57",
        "instance_58",
        "instance_59",
        "instance_60",
        "instance_61",
        "instance_62",
        "instance_63",
        ),
    ENDIAN=">", SIZE=20
    )


hlmt_instance_group = Struct("instance_groups",
    string_id_meta("name"),
    SInt32("unknown"),
    reflexive("instance_members", hlmt_instance_group_instance_member),
    Float("probability"),
    ENDIAN=">", SIZE=24
    )


hlmt_material = Struct("materials",
    string_id_meta("name"),
    SInt16("unknown"),
    SInt16("damage_section_index"),
    SInt16("unknown_1"),
    SInt16("unknown_2"),
    string_id_meta("material_name"),
    SInt16("global_material_index"),
    SInt16("unknown_3"),
    ENDIAN=">", SIZE=20
    )


hlmt_new_damage_info_damage_section_instant_response = Struct("instant_responses",
    SEnum16("response_type", *hlmt_new_damage_info_damage_section_instant_response_response_type),
    SEnum16("constraint_damage_type", *hlmt_new_damage_info_damage_section_instant_response_constraint_damage_type),
    string_id_meta("trigger"),
    Bool32("flags",
        "kills_object",
        "inhibits_melee_attack",
        "inhibits_weapon_attack",
        "inhibits_walking",
        "forces_drop_weapon",
        "kills_weapon_primary_trigger",
        "kills_weapon_secondary_trigger",
        "destroys_object",
        "damages_weapon_primary_trigger",
        "damages_weapon_secondary_trigger",
        "light_damage_left_turn",
        "major_damage_left_turn",
        "light_damage_right_turn",
        "major_damage_right_turn",
        "light_damage_engine",
        "major_damage_engine",
        "kills_object_no_player_solo",
        "causes_detonation",
        "destroy_all_group_constraints",
        "kills_variant_objects",
        "force_unattached_effects",
        "fires_under_threshold",
        "triggers_special_death",
        "only_on_special_death",
        "only_not_on_special_death",
        ("causes_detonation_in_single_player", 1 << 26),
        ),
    Float("damage_threshold"),
    dependency("primary_transition_effect"),
    dependency("secondary_transition_effect"),
    dependency("transition_damage_effect"),
    string_id_meta("region"),
    SEnum16("new_state", *hlmt_variant_region_permutation_state_state),
    SInt16("runtime_region_index"),
    string_id_meta("secondary_region"),
    SEnum16("secondary_new_state", *hlmt_variant_region_permutation_state_state),
    SInt16("secondary_runtime_region_index"),
    SInt16("unknown"),
    SEnum16("unknown_special_damage", *hlmt_new_damage_info_damage_section_instant_response_unknown_special_damage),
    string_id_meta("special_damage_case"),
    string_id_meta("effect_marker_name"),
    string_id_meta("damage_effect_marker_name"),
    Float("response_delay"),
    dependency("delay_effect"),
    string_id_meta("delay_effect_marker_name"),
    string_id_meta("ejecting_seat_label"),
    Float("skip_fraction"),
    string_id_meta("destroyed_child_object_marker_name"),
    Float("total_damage_threshold"),
    ENDIAN=">", SIZE=136
    )


hlmt_new_damage_info_damage_section = Struct("damage_sections",
    string_id_meta("name"),
    Bool32("flags",
        "absorbs_body_damage",
        "takes_full_damage_when_object_dies",
        "cannot_die_with_riders",
        "takes_full_damage_when_object_destroyed",
        "restored_on_ressurection",
        ("headshotable", 1 << 7),
        "ignores_shields",
        ),
    Float("vitality_percentage"),
    reflexive("instant_responses", hlmt_new_damage_info_damage_section_instant_response),
    Pad(24),
    Float("stun_time"),
    Float("recharge_time"),
    Float("unknown_1"),
    string_id_meta("resurrection_region_name"),
    SInt16("ressurection_region_runtime_index"),
    SInt16("unknown_2"),
    ENDIAN=">", SIZE=68
    )


hlmt_new_damage_info_node = Struct("nodes",
    SInt16("unknown"),
    SInt16("unknown_1"),
    Pad(12),
    ENDIAN=">", SIZE=16
    )


hlmt_new_damage_info_damage_seat_unknown = Struct("unknown",
    string_id_meta("node"),
    SInt16("unknown"),
    SInt16("unknown_1"),
    Pad(36),
    ENDIAN=">", SIZE=44
    )


hlmt_new_damage_info_damage_seat = Struct("damage_seats",
    string_id_meta("seat_label"),
    Float("direct_damage_scale"),
    Float("damage_transfer_fall_off_radius"),
    Float("maximum_transfer_damage_scale"),
    Float("minimum_transfer_damage_scale"),
    reflexive("unknown", hlmt_new_damage_info_damage_seat_unknown),
    ENDIAN=">", SIZE=32
    )


hlmt_new_damage_info_damage_constraint = Struct("damage_constraints",
    string_id_meta("physics_model_constraint_name"),
    string_id_meta("damage_constraint_name"),
    string_id_meta("damage_constraint_group_name"),
    Float("group_probability_scale"),
    SEnum16("type", *hlmt_new_damage_info_damage_constraint_type),
    SInt16("idx"),
    ENDIAN=">", SIZE=20
    )


hlmt_new_damage_info = Struct("new_damage_info",
    Bool32("flags",
        "takes_shield_damage_for_children",
        "takes_body_damage_for_children",
        "always_shields_friendly_damage",
        "passes_area_damage_to_children",
        "parent_never_takes_body_damage_for_children",
        "only_damaged_by_explosives",
        "parent_never_takes_shield_damage_for_children",
        "cannot_die_from_damage",
        "passes_attached_damage_to_riders",
        ("only_damaged_by_player", 1 << 11),
        ),
    string_id_meta("global_indirect_material_name"),
    SInt16("indirect_damage_section"),
    SInt16("unknown"),
    Pad(4),
    SEnum8("collision_damage_reporting_type", *hlmt_new_damage_info_collision_damage_reporting_type),
    SEnum8("response_damage_reporting_type", *hlmt_new_damage_info_collision_damage_reporting_type),
    SInt16("unknown_2"),
    Pad(20),
    Float("maximum_vitality"),
    Float("minimum_stun_damage"),
    Float("stun_time"),
    Float("recharge_time"),
    Float("recharge_fraction"),
    Pad(64),
    Float("maximum_shield_vitality"),
    string_id_meta("global_shield_material_name"),
    Float("minimum_stun_damage_1"),
    Float("stun_time_1"),
    Float("shield_recharge_time"),
    Float("shield_damaged_threshold"),
    dependency("shield_damaged_effect"),
    dependency("shield_depleted_effect"),
    dependency("shield_recharging_effect"),
    reflexive("damage_sections", hlmt_new_damage_info_damage_section),
    reflexive("nodes", hlmt_new_damage_info_node),
    SInt16("global_shield_material_index"),
    SInt16("global_indirect_material_index"),
    Float("unknown_5"),
    Float("unknown_6"),
    reflexive("damage_seats", hlmt_new_damage_info_damage_seat),
    reflexive("damage_constraints", hlmt_new_damage_info_damage_constraint),
    ENDIAN=">", SIZE=256
    )


hlmt_target = Struct("targets",
    string_id_meta("marker_name"),
    Float("size"),
    float_rad("cone_angle"),
    SInt16("damage_section"),
    SInt16("variant"),
    Float("targeting_relevance"),
    Pad(4),
    Bool32("flags",
        "locked_by_human_tracking",
        "locked_by_plasma_tracking",
        "headshot",
        ("vulnerable", 1 << 4),
        ("always_locked_by_plasma_tracking", 1 << 6),
        ),
    Float("lock_on_distance"),
    ENDIAN=">", SIZE=32
    )


hlmt_collision_region_permutation = Struct("permutations",
    string_id_meta("name"),
    Bool8("flags",
        "cannot_be_chosen_randomly",
        ),
    SInt8("collision_permutation_index"),
    SInt8("physics_permutation_index"),
    SInt8("unknown"),
    ENDIAN=">", SIZE=8
    )


hlmt_collision_region = Struct("collision_regions",
    string_id_meta("name"),
    SInt8("collision_region_index"),
    SInt8("physics_region_index"),
    SInt8("unknown"),
    SInt8("unknown_1"),
    reflexive("permutations", hlmt_collision_region_permutation),
    ENDIAN=">", SIZE=20
    )


hlmt_node = Struct("nodes",
    string_id_meta("name"),
    SInt16("parent_node"),
    SInt16("first_child_node"),
    SInt16("next_sibling_node"),
    SInt16("import_node_index"),
    Float("default_translation_x"),
    Float("default_translation_y"),
    Float("default_translation_z"),
    Float("default_rotation_i"),
    Float("default_rotation_j"),
    Float("default_rotation_k"),
    Float("default_rotation_w"),
    Float("default_scale"),
    Float("inverse_forward_i"),
    Float("inverse_forward_j"),
    Float("inverse_forward_k"),
    Float("inverse_left_i"),
    Float("inverse_left_j"),
    Float("inverse_left_k"),
    Float("inverse_up_i"),
    Float("inverse_up_j"),
    Float("inverse_up_k"),
    Float("inverse_position_x"),
    Float("inverse_position_y"),
    Float("inverse_position_z"),
    ENDIAN=">", SIZE=92
    )


hlmt_model_object_data = Struct("model_object_data",
    SEnum16("type", *hlmt_model_object_data_type),
    SInt16("unknown"),
    Float("offset_x"),
    Float("offset_y"),
    Float("offset_z"),
    Float("radius"),
    ENDIAN=">", SIZE=20
    )


hlmt_unknown_3 = Struct("unknown_3",
    string_id_meta("region"),
    string_id_meta("permutation"),
    ENDIAN=">", SIZE=8
    )


hlmt_unknown_4 = Struct("unknown_4",
    string_id_meta("unknown"),
    Pad(4),
    ENDIAN=">", SIZE=8
    )


hlmt_unknown_5 = Struct("unknown_5",
    string_id_meta("marker"),
    Pad(4),
    string_id_meta("marker_1"),
    Pad(8),
    ENDIAN=">", SIZE=20
    )


hlmt_meta_def = BlockDef("hlmt",
    dependency("model"),
    dependency("collision_model"),
    dependency("animation"),
    dependency("physics_model"),
    Float("reduce_to_l1_super_low"),
    Float("reduce_to_l2_low"),
    Float("reduce_to_l3_medium"),
    Float("reduce_to_l4_high"),
    Float("reduce_to_l5_super_high"),
    dependency("lod_model"),
    reflexive("variants", hlmt_variant),
    reflexive("instance_groups", hlmt_instance_group),
    reflexive("materials", hlmt_material),
    reflexive("new_damage_info", hlmt_new_damage_info),
    reflexive("targets", hlmt_target),
    reflexive("collision_regions", hlmt_collision_region),
    reflexive("nodes", hlmt_node),
    Pad(4),
    reflexive("model_object_data", hlmt_model_object_data),
    dependency("primary_dialog"),
    dependency("secondary_dialog"),
    Bool32("flags",
        "active_camo_always_on",
        "active_camo_always_merge",
        "active_camo_never_merge",
        ),
    string_id_meta("default_dialogue_effect"),
    Bool32("render_only_node_flags_1",
        "node_0",
        "node_1",
        "node_2",
        "node_3",
        "node_4",
        "node_5",
        "node_6",
        "node_7",
        "node_8",
        "node_9",
        "node_10",
        "node_11",
        "node_12",
        "node_13",
        "node_14",
        "node_15",
        "node_16",
        "node_17",
        "node_18",
        "node_19",
        "node_20",
        "node_21",
        "node_22",
        "node_23",
        "node_24",
        "node_25",
        "node_26",
        "node_27",
        "node_28",
        "node_29",
        "node_30",
        "node_31",
        ),
    Bool32("render_only_node_flags_2",
        "node_32",
        "node_33",
        "node_34",
        "node_35",
        "node_36",
        "node_37",
        "node_38",
        "node_39",
        "node_40",
        "node_41",
        "node_42",
        "node_43",
        "node_44",
        "node_45",
        "node_46",
        "node_47",
        "node_48",
        "node_49",
        "node_50",
        "node_51",
        "node_52",
        "node_53",
        "node_54",
        "node_55",
        "node_56",
        "node_57",
        "node_58",
        "node_59",
        "node_60",
        "node_61",
        "node_62",
        "node_63",
        ),
    Bool32("render_only_node_flags_3",
        "node_64",
        "node_65",
        "node_66",
        "node_67",
        "node_68",
        "node_69",
        "node_70",
        "node_71",
        "node_72",
        "node_73",
        "node_74",
        "node_75",
        "node_76",
        "node_77",
        "node_78",
        "node_79",
        "node_80",
        "node_81",
        "node_82",
        "node_83",
        "node_84",
        "node_85",
        "node_86",
        "node_87",
        "node_88",
        "node_89",
        "node_90",
        "node_91",
        "node_92",
        "node_93",
        "node_94",
        "node_95",
        ),
    Bool32("render_only_node_flags_4",
        "node_96",
        "node_97",
        "node_98",
        "node_99",
        "node_100",
        "node_101",
        "node_102",
        "node_103",
        "node_104",
        "node_105",
        "node_106",
        "node_107",
        "node_108",
        "node_109",
        "node_110",
        "node_111",
        "node_112",
        "node_113",
        "node_114",
        "node_115",
        "node_116",
        "node_117",
        "node_118",
        "node_119",
        "node_120",
        "node_121",
        "node_122",
        "node_123",
        "node_124",
        "node_125",
        "node_126",
        "node_127",
        ),
    Bool32("render_only_node_flags_5",
        "node_128",
        "node_129",
        "node_130",
        "node_131",
        "node_132",
        "node_133",
        "node_134",
        "node_135",
        "node_136",
        "node_137",
        "node_138",
        "node_139",
        "node_140",
        "node_141",
        "node_142",
        "node_143",
        "node_144",
        "node_145",
        "node_146",
        "node_147",
        "node_148",
        "node_149",
        "node_150",
        "node_151",
        "node_152",
        "node_153",
        "node_154",
        "node_155",
        "node_156",
        "node_157",
        "node_158",
        "node_159",
        ),
    Bool32("render_only_node_flags_6",
        "node_160",
        "node_161",
        "node_162",
        "node_163",
        "node_164",
        "node_165",
        "node_166",
        "node_167",
        "node_168",
        "node_169",
        "node_170",
        "node_171",
        "node_172",
        "node_173",
        "node_174",
        "node_175",
        "node_176",
        "node_177",
        "node_178",
        "node_179",
        "node_180",
        "node_181",
        "node_182",
        "node_183",
        "node_184",
        "node_185",
        "node_186",
        "node_187",
        "node_188",
        "node_189",
        "node_190",
        "node_191",
        ),
    Bool32("render_only_node_flags_7",
        "node_192",
        "node_193",
        "node_194",
        "node_195",
        "node_196",
        "node_197",
        "node_198",
        "node_199",
        "node_200",
        "node_201",
        "node_202",
        "node_203",
        "node_204",
        "node_205",
        "node_206",
        "node_207",
        "node_208",
        "node_209",
        "node_210",
        "node_211",
        "node_212",
        "node_213",
        "node_214",
        "node_215",
        "node_216",
        "node_217",
        "node_218",
        "node_219",
        "node_220",
        "node_221",
        "node_222",
        "node_223",
        ),
    Bool32("render_only_node_flags_8",
        "node_224",
        "node_225",
        "node_226",
        "node_227",
        "node_228",
        "node_229",
        "node_230",
        "node_231",
        "node_232",
        "node_233",
        "node_234",
        "node_235",
        "node_236",
        "node_237",
        "node_238",
        "node_239",
        "node_240",
        "node_241",
        "node_242",
        "node_243",
        "node_244",
        "node_245",
        "node_246",
        "node_247",
        "node_248",
        "node_249",
        "node_250",
        "node_251",
        "node_252",
        "node_253",
        "node_254",
        "node_255",
        ),
    Bool32("render_only_section_flags_1",
        "section_0",
        "section_1",
        "section_2",
        "section_3",
        "section_4",
        "section_5",
        "section_6",
        "section_7",
        "section_8",
        "section_9",
        "section_10",
        "section_11",
        "section_12",
        "section_13",
        "section_14",
        "section_15",
        "section_16",
        "section_17",
        "section_18",
        "section_19",
        "section_20",
        "section_21",
        "section_22",
        "section_23",
        "section_24",
        "section_25",
        "section_26",
        "section_27",
        "section_28",
        "section_29",
        "section_30",
        "section_31",
        ),
    Bool32("render_only_section_flags_2",
        "section_32",
        "section_33",
        "section_34",
        "section_35",
        "section_36",
        "section_37",
        "section_38",
        "section_39",
        "section_40",
        "section_41",
        "section_42",
        "section_43",
        "section_44",
        "section_45",
        "section_46",
        "section_47",
        "section_48",
        "section_49",
        "section_50",
        "section_51",
        "section_52",
        "section_53",
        "section_54",
        "section_55",
        "section_56",
        "section_57",
        "section_58",
        "section_59",
        "section_60",
        "section_61",
        "section_62",
        "section_63",
        ),
    Bool32("render_only_section_flags_3",
        "section_64",
        "section_65",
        "section_66",
        "section_67",
        "section_68",
        "section_69",
        "section_70",
        "section_71",
        "section_72",
        "section_73",
        "section_74",
        "section_75",
        "section_76",
        "section_77",
        "section_78",
        "section_79",
        "section_80",
        "section_81",
        "section_82",
        "section_83",
        "section_84",
        "section_85",
        "section_86",
        "section_87",
        "section_88",
        "section_89",
        "section_90",
        "section_91",
        "section_92",
        "section_93",
        "section_94",
        "section_95",
        ),
    Bool32("render_only_section_flags_4",
        "section_96",
        "section_97",
        "section_98",
        "section_99",
        "section_100",
        "section_101",
        "section_102",
        "section_103",
        "section_104",
        "section_105",
        "section_106",
        "section_107",
        "section_108",
        "section_109",
        "section_110",
        "section_111",
        "section_112",
        "section_113",
        "section_114",
        "section_115",
        "section_116",
        "section_117",
        "section_118",
        "section_119",
        "section_120",
        "section_121",
        "section_122",
        "section_123",
        "section_124",
        "section_125",
        "section_126",
        "section_127",
        ),
    Bool32("render_only_section_flags_5",
        "section_128",
        "section_129",
        "section_130",
        "section_131",
        "section_132",
        "section_133",
        "section_134",
        "section_135",
        "section_136",
        "section_137",
        "section_138",
        "section_139",
        "section_140",
        "section_141",
        "section_142",
        "section_143",
        "section_144",
        "section_145",
        "section_146",
        "section_147",
        "section_148",
        "section_149",
        "section_150",
        "section_151",
        "section_152",
        "section_153",
        "section_154",
        "section_155",
        "section_156",
        "section_157",
        "section_158",
        "section_159",
        ),
    Bool32("render_only_section_flags_6",
        "section_160",
        "section_161",
        "section_162",
        "section_163",
        "section_164",
        "section_165",
        "section_166",
        "section_167",
        "section_168",
        "section_169",
        "section_170",
        "section_171",
        "section_172",
        "section_173",
        "section_174",
        "section_175",
        "section_176",
        "section_177",
        "section_178",
        "section_179",
        "section_180",
        "section_181",
        "section_182",
        "section_183",
        "section_184",
        "section_185",
        "section_186",
        "section_187",
        "section_188",
        "section_189",
        "section_190",
        "section_191",
        ),
    Bool32("render_only_section_flags_7",
        "section_192",
        "section_193",
        "section_194",
        "section_195",
        "section_196",
        "section_197",
        "section_198",
        "section_199",
        "section_200",
        "section_201",
        "section_202",
        "section_203",
        "section_204",
        "section_205",
        "section_206",
        "section_207",
        "section_208",
        "section_209",
        "section_210",
        "section_211",
        "section_212",
        "section_213",
        "section_214",
        "section_215",
        "section_216",
        "section_217",
        "section_218",
        "section_219",
        "section_220",
        "section_221",
        "section_222",
        "section_223",
        ),
    Bool32("render_only_section_flags_8",
        "section_224",
        "section_225",
        "section_226",
        "section_227",
        "section_228",
        "section_229",
        "section_230",
        "section_231",
        "section_232",
        "section_233",
        "section_234",
        "section_235",
        "section_236",
        "section_237",
        "section_238",
        "section_239",
        "section_240",
        "section_241",
        "section_242",
        "section_243",
        "section_244",
        "section_245",
        "section_246",
        "section_247",
        "section_248",
        "section_249",
        "section_250",
        "section_251",
        "section_252",
        "section_253",
        "section_254",
        "section_255",
        ),
    Bool32("runtime_flags",
        "contains_runtime_nodes",
        ),
    Pad(12),
    SInt16("unknown_1"),
    SInt16("unknown_2"),
    reflexive("unknown_3", hlmt_unknown_3),
    reflexive("unknown_4", hlmt_unknown_4),
    reflexive("unknown_5", hlmt_unknown_5),
    dependency("shield_impact_third_person"),
    dependency("shield_impact_first_person"),
    TYPE=Struct, ENDIAN=">", SIZE=392
    )
