############# Credits and version info #############
# Definition autogenerated from Assembly XML tag def
#
# revision: 1		author: Assembly
# 	Generated plugin from scratch.
# revision: 2		author: -DeToX-
# 	Named Some Values...
# revision: 3		author: Halodu03de
# 	added chunk code
# revision: 4		author: Lord Zedd
# 	Lots of updates
# revision: 5		author: Moses_of_Egypt
# 	Cleaned up and converted to SuPyr definition
#
####################################################
from reclaimer.common_descs import *
from supyr_struct.defs.tag_def import TagDef

hlmt_model_object_data_type = (
    "not_set",
    "user_defined",
    "auto_generated",
    )

hlmt_new_damage_info_collision_damage_reporting_type = (
    "guardians",
    "falling_damage",
    "collision",
    "melee",
    "explosion",
    "magnum",
    "plasma_pistol",
    "needler",
    "mauler",
    "smg",
    "plasma_rifle",
    "battle_rifle",
    "carbine",
    "shotgun",
    "sniper_rifle",
    "beam_rifle",
    "assault_rifle",
    "spiker",
    "fuel_rod_cannon",
    "missile_pod",
    "rocket_launcher",
    "spartan_laser",
    "brute_shot",
    "flamethrower",
    "sentinel_gun",
    "energy_sword",
    "gravity_hammer",
    "frag_grenade",
    "plasma_grenade",
    "spike_grenade",
    "firebomb_grenade",
    "flag",
    "bomb",
    "bomb_explosion",
    "ball",
    "machinegun_turret",
    "plasma_cannon",
    "plasma_mortar",
    "plasma_turret",
    "banshee",
    "ghost",
    "mongoose",
    "scorpion",
    "scorpion_gunner",
    "spectre",
    "spectre_gunner",
    "warthog",
    "warthog_gunner",
    "warthog_gauss_turret",
    "wraith",
    "wraith_gunner",
    "tank",
    "chopper",
    "hornet",
    "mantis",
    "prowler",
    "sentinel_beam",
    "sentinel_rpg",
    "teleporter",
    "tripmine",
    "elephant_turret",
    )

hlmt_new_damage_info_damage_constraint_type = (
    "hinge",
    "limited_hinge",
    "ragdoll",
    "stiff_spring",
    "ball_and_socket",
    "prismatic",
    )

hlmt_new_damage_info_damage_section_instant_response_constraint_damage_type = (
    "none",
    "destroy_one_of_group",
    "destroy_entire_group",
    "loosen_one_of_group",
    "loosen_entire_group",
    )

hlmt_new_damage_info_damage_section_instant_response_response_type = (
    "recieves_all_damage",
    "recieves_area_effect_damage",
    "recieves_local_damage",
    )

hlmt_new_damage_info_damage_section_instant_response_unknown_special_damage = (
    "none",
    "_1",
    "_2",
    "_3",
    )

hlmt_variant_region_permutation_state_state = (
    "default",
    "minor_damage",
    "medium_damage",
    "major_damage",
    "destroyed",
    )

hlmt_variant_region_sort_order = (
    "no_sorting",
    "neg_5_closest",
    "neg_4",
    "neg_3",
    "neg_2",
    "neg_1",
    "_0_same_as_model",
    "_1",
    "_2",
    "_3",
    "_4",
    "_5_farthest",
    )


hlmt_variant_region_permutation_state = Struct("state", 
    string_id_meta("name"),
    SInt8("model_permutation_index"),
    Bool8("property_flags", 
        "blurred",
        "hella_blurred",
        "shielded",
        ),
    SEnum16("state", *hlmt_variant_region_permutation_state_state),
    dependency("looping_effect"),
    string_id_meta("looping_effect_marker_name"),
    Float("initial_probability"),
    ENDIAN=">", SIZE=32
    )


hlmt_variant_region_permutation = Struct("permutation", 
    string_id_meta("name"),
    SInt8("model_permutation_index"),
    Bool8("flags", 
        "copy_states_to_all_permutations",
        ),
    SInt8("unknown_0", VISIBLE=False),
    SInt8("unknown_1", VISIBLE=False),
    Float("probability"),
    reflexive("states", hlmt_variant_region_permutation_state),
    BytesRaw("unknown_2", SIZE=12, VISIBLE=False),
    ENDIAN=">", SIZE=36
    )


hlmt_variant_region = Struct("region", 
    string_id_meta("name"),
    SInt8("model_region_index"),
    SInt8("unknown", VISIBLE=False),
    SInt16("parent_variant_index"),
    reflexive("permutations", hlmt_variant_region_permutation),
    SEnum32("sort_order", *hlmt_variant_region_sort_order),
    ENDIAN=">", SIZE=24
    )


hlmt_variant_object = Struct("object", 
    string_id_meta("parent_marker"),
    string_id_meta("child_marker"),
    string_id_meta("child_variant"),
    dependency("child_object"),
    ENDIAN=">", SIZE=28
    )


hlmt_variant = Struct("variant", 
    string_id_meta("name"),
    Array("model_region_index_array", SUB_STRUCT=SInt8("model_region_index"), SIZE=16),
    reflexive("regions", hlmt_variant_region),
    reflexive("objects", hlmt_variant_object),
    SInt32("instance_group_index"),
    BytesRaw("unknown", SIZE=8, VISIBLE=False),
    ENDIAN=">", SIZE=56
    )


hlmt_instance_group_instance_member = Struct("instance_member", 
    SInt32("unknown", VISIBLE=False),
    string_id_meta("instance_name"),
    Float("probability"),
    Bool32("instance_flags_1", *("instance_%s" % i for i in range(32))),
    Bool32("instance_flags_2", *("instance_%s" % i for i in range(32, 64))),
    ENDIAN=">", SIZE=20
    )


hlmt_instance_group = Struct("instance_group", 
    string_id_meta("name"),
    SInt32("unknown", VISIBLE=False),
    reflexive("instance_members", hlmt_instance_group_instance_member),
    Float("probability"),
    ENDIAN=">", SIZE=24
    )


hlmt_material = Struct("material", 
    string_id_meta("name"),
    SInt16("unknown_0", VISIBLE=False),
    SInt16("damage_section_index"),
    SInt16("unknown_1", VISIBLE=False),
    SInt16("unknown_2", VISIBLE=False),
    string_id_meta("material_name"),
    SInt16("global_material_index"),
    SInt16("unknown_3", VISIBLE=False),
    ENDIAN=">", SIZE=20
    )


hlmt_new_damage_info_damage_section_instant_response = Struct("instant_response", 
    SEnum16("response_type", *hlmt_new_damage_info_damage_section_instant_response_response_type),
    SEnum16("constraint_damage_type", *hlmt_new_damage_info_damage_section_instant_response_constraint_damage_type),
    string_id_meta("trigger"),
    Bool32("flags", 
        "kills_object",
        "inhibits_melee_attack",
        "inhibits_weapon_attack",
        "inhibits_walking",
        "forces_drop_weapon",
        "kills_weapon_primary_trigger",
        "kills_weapon_secondary_trigger",
        "destroys_object",
        "damages_weapon_primary_trigger",
        "damages_weapon_secondary_trigger",
        "light_damage_left_turn",
        "major_damage_left_turn",
        "light_damage_right_turn",
        "major_damage_right_turn",
        "light_damage_engine",
        "major_damage_engine",
        "kills_object_no_player_solo",
        "causes_detonation",
        "destroy_all_group_constraints",
        "kills_variant_objects",
        "force_unattached_effects",
        "fires_under_threshold",
        "triggers_special_death",
        "only_on_special_death",
        "only_not_on_special_death",
        ("causes_detonation_in_single_player", 1 << 26),
        ),
    Float("damage_threshold"),
    dependency("primary_transition_effect"),
    dependency("secondary_transition_effect"),
    dependency("transition_damage_effect"),
    string_id_meta("region"),
    SEnum16("new_state", *hlmt_variant_region_permutation_state_state),
    SInt16("runtime_region_index"),
    string_id_meta("secondary_region"),
    SEnum16("secondary_new_state", *hlmt_variant_region_permutation_state_state),
    SInt16("secondary_runtime_region_index"),
    SInt16("unknown"),
    SEnum16("unknown_special_damage", *hlmt_new_damage_info_damage_section_instant_response_unknown_special_damage),
    string_id_meta("special_damage_case"),
    string_id_meta("effect_marker_name"),
    string_id_meta("damage_effect_marker_name"),
    Float("response_delay"),
    dependency("delay_effect"),
    string_id_meta("delay_effect_marker_name"),
    string_id_meta("ejecting_seat_label"),
    Float("skip_fraction"),
    string_id_meta("destroyed_child_object_marker_name"),
    Float("total_damage_threshold"),
    ENDIAN=">", SIZE=136
    )


hlmt_new_damage_info_damage_section = Struct("damage_section", 
    string_id_meta("name"),
    Bool32("flags", 
        "absorbs_body_damage",
        "takes_full_damage_when_object_dies",
        "cannot_die_with_riders",
        "takes_full_damage_when_object_destroyed",
        "restored_on_ressurection",
        ("headshotable", 1 << 7),
        "ignores_shields",
        ),
    Float("vitality_percentage"),
    reflexive("instant_responses", hlmt_new_damage_info_damage_section_instant_response),
    BytesRaw("unknown_0", SIZE=24, VISIBLE=False),
    Float("stun_time"),
    Float("recharge_time"),
    Float("unknown_1", VISIBLE=False),
    string_id_meta("resurrection_region_name"),
    SInt16("ressurection_region_runtime_index"),
    SInt16("unknown_2", VISIBLE=False),
    ENDIAN=">", SIZE=68
    )


hlmt_new_damage_info_node = Struct("node", 
    SInt16("unknown_0", VISIBLE=False),
    SInt16("unknown_1", VISIBLE=False),
    BytesRaw("unknown_2", SIZE=12, VISIBLE=False),
    VISIBLE=False,
    ENDIAN=">", SIZE=16
    )


hlmt_new_damage_info_damage_seat_unknown = Struct("unknown", 
    string_id_meta("node"),
    SInt16("unknown_0", VISIBLE=False),
    SInt16("unknown_1", VISIBLE=False),
    BytesRaw("unknown_2", SIZE=36, VISIBLE=False),
    VISIBLE=False,
    ENDIAN=">", SIZE=44
    )


hlmt_new_damage_info_damage_seat = Struct("damage_seat", 
    string_id_meta("seat_label"),
    Float("direct_damage_scale"),
    Float("damage_transfer_fall_off_radius"),
    Float("maximum_transfer_damage_scale"),
    Float("minimum_transfer_damage_scale"),
    reflexive("unknown", hlmt_new_damage_info_damage_seat_unknown),
    ENDIAN=">", SIZE=32
    )


hlmt_new_damage_info_damage_constraint = Struct("damage_constraint", 
    string_id_meta("physics_model_constraint_name"),
    string_id_meta("damage_constraint_name"),
    string_id_meta("damage_constraint_group_name"),
    Float("group_probability_scale"),
    SEnum16("type", *hlmt_new_damage_info_damage_constraint_type),
    SInt16("idx"),
    ENDIAN=">", SIZE=20
    )


hlmt_new_damage_info = Struct("new_damage_info", 
    Bool32("flags", 
        "takes_shield_damage_for_children",
        "takes_body_damage_for_children",
        "always_shields_friendly_damage",
        "passes_area_damage_to_children",
        "parent_never_takes_body_damage_for_children",
        "only_damaged_by_explosives",
        "parent_never_takes_shield_damage_for_children",
        "cannot_die_from_damage",
        "passes_attached_damage_to_riders",
        ("only_damaged_by_player", 1 << 11),
        ),
    string_id_meta("global_indirect_material_name"),
    SInt16("indirect_damage_section"),
    SInt16("unknown_0", VISIBLE=False),
    BytesRaw("unknown_1", SIZE=4, VISIBLE=False),
    SEnum8("collision_damage_reporting_type", *hlmt_new_damage_info_collision_damage_reporting_type),
    SEnum8("response_damage_reporting_type", *hlmt_new_damage_info_collision_damage_reporting_type),
    SInt16("unknown_2", VISIBLE=False),
    BytesRaw("unknown_3", SIZE=20, VISIBLE=False),
    Float("maximum_vitality"),
    Float("minimum_stun_damage_0"),
    Float("stun_time_0"),
    Float("recharge_time"),
    Float("recharge_fraction"),
    Pad(64),
    Float("maximum_shield_vitality"),
    string_id_meta("global_shield_material_name"),
    Float("minimum_stun_damage_1"),
    Float("stun_time_1"),
    Float("shield_recharge_time"),
    Float("shield_damaged_threshold"),
    dependency("shield_damaged_effect"),
    dependency("shield_depleted_effect"),
    dependency("shield_recharging_effect"),
    reflexive("damage_sections", hlmt_new_damage_info_damage_section),
    reflexive("nodes", hlmt_new_damage_info_node),
    SInt16("global_shield_material_index"),
    SInt16("global_indirect_material_index"),
    Float("unknown_5", VISIBLE=False),
    Float("unknown_6", VISIBLE=False),
    reflexive("damage_seats", hlmt_new_damage_info_damage_seat),
    reflexive("damage_constraints", hlmt_new_damage_info_damage_constraint),
    ENDIAN=">", SIZE=256
    )


hlmt_target = Struct("target", 
    string_id_meta("marker_name"),
    Float("size"),
    float_rad("cone_angle", VISIBLE=False),
    SInt16("damage_section"),
    SInt16("variant"),
    Float("targeting_relevance"),
    BytesRaw("unknown", SIZE=4, VISIBLE=False),
    Bool32("flags", 
        "locked_by_human_tracking",
        "locked_by_plasma_tracking",
        "headshot",
        ("vulnerable", 1 << 4),
        ("always_locked_by_plasma_tracking", 1 << 6),
        ),
    Float("lock_on_distance"),
    VISIBLE=False,
    ENDIAN=">", SIZE=32
    )


hlmt_collision_region_permutation = Struct("permutation", 
    string_id_meta("name"),
    Bool8("flags", 
        "cannot_be_chosen_randomly",
        ),
    SInt8("collision_permutation_index"),
    SInt8("physics_permutation_index"),
    SInt8("unknown", VISIBLE=False),
    ENDIAN=">", SIZE=8
    )


hlmt_collision_region = Struct("collision_region", 
    string_id_meta("name"),
    SInt8("collision_region_index"),
    SInt8("physics_region_index"),
    SInt8("unknown_0", VISIBLE=False),
    SInt8("unknown_1", VISIBLE=False),
    reflexive("permutations", hlmt_collision_region_permutation),
    ENDIAN=">", SIZE=20
    )


hlmt_node = Struct("node", 
    string_id_meta("name"),
    SInt16("parent_node"),
    SInt16("first_child_node"),
    SInt16("next_sibling_node"),
    SInt16("import_node_index"),
    QStruct("default_translation", INCLUDE=xyz_float),
    QStruct("default_rotation", INCLUDE=ijkw_float),
    Float("default_scale"),
    QStruct("inverse_forward", INCLUDE=ijk_float),
    QStruct("inverse_left", INCLUDE=ijk_float),
    QStruct("inverse_up", INCLUDE=ijk_float),
    QStruct("inverse_position", INCLUDE=xyz_float),
    ENDIAN=">", SIZE=92
    )


hlmt_model_object_data = Struct("model_object_data", 
    SEnum16("type", *hlmt_model_object_data_type),
    SInt16("unknown", VISIBLE=False),
    QStruct("offset", INCLUDE=xyz_float),
    Float("radius"),
    ENDIAN=">", SIZE=20
    )


hlmt_unknown_3 = Struct("unknown_3", 
    string_id_meta("region"),
    string_id_meta("permutation"),
    VISIBLE=False,
    ENDIAN=">", SIZE=8
    )


hlmt_unknown_4 = Struct("unknown_4", 
    string_id_meta("unknown_0", VISIBLE=False),
    BytesRaw("unknown_1", SIZE=4, VISIBLE=False),
    VISIBLE=False,
    ENDIAN=">", SIZE=8
    )


hlmt_unknown_5 = Struct("unknown_5", 
    string_id_meta("marker_0", VISIBLE=False),
    BytesRaw("unknown_0", SIZE=4, VISIBLE=False),
    string_id_meta("marker_1", VISIBLE=False),
    BytesRaw("unknown_1", SIZE=8, VISIBLE=False),
    VISIBLE=False,
    ENDIAN=">", SIZE=20
    )


hlmt_meta_def = BlockDef("hlmt", 
    dependency("model"),
    dependency("collision_model"),
    dependency("animation"),
    dependency("physics_model"),
    Float("reduce_to_l1_super_low"),
    Float("reduce_to_l2_low"),
    Float("reduce_to_l3_medium"),
    Float("reduce_to_l4_high"),
    Float("reduce_to_l5_super_high"),
    dependency("lod_model"),
    reflexive("variants", hlmt_variant),
    reflexive("instance_groups", hlmt_instance_group),
    reflexive("materials", hlmt_material),
    reflexive("new_damage_info", hlmt_new_damage_info),
    reflexive("targets", hlmt_target),
    reflexive("collision_regions", hlmt_collision_region),
    reflexive("nodes", hlmt_node),
    BytesRaw("unknown_0", SIZE=4, VISIBLE=False),
    reflexive("model_object_data", hlmt_model_object_data),
    dependency("primary_dialog"),
    dependency("secondary_dialog"),
    Bool32("flags", 
        "active_camo_always_on",
        "active_camo_always_merge",
        "active_camo_never_merge",
        ),
    string_id_meta("default_dialogue_effect"),
    Bool32("render_only_node_flags_1", *("node_%s" % i for i in range(32)), VISIBLE=False),
    Bool32("render_only_node_flags_2", *("node_%s" % i for i in range(32, 64)), VISIBLE=False),
    Bool32("render_only_node_flags_3", *("node_%s" % i for i in range(64, 96)), VISIBLE=False),
    Bool32("render_only_node_flags_4", *("node_%s" % i for i in range(96, 128)), VISIBLE=False),
    Bool32("render_only_node_flags_5", *("node_%s" % i for i in range(128, 160)), VISIBLE=False),
    Bool32("render_only_node_flags_6", *("node_%s" % i for i in range(160, 192)), VISIBLE=False),
    Bool32("render_only_node_flags_7", *("node_%s" % i for i in range(192, 224)), VISIBLE=False),
    Bool32("render_only_node_flags_8", *("node_%s" % i for i in range(224, 256)), VISIBLE=False),
    Bool32("render_only_section_flags_1", *("section_%s" % i for i in range(32)), VISIBLE=False),
    Bool32("render_only_section_flags_2", *("section_%s" % i for i in range(32, 64)), VISIBLE=False),
    Bool32("render_only_section_flags_3", *("section_%s" % i for i in range(64, 96)), VISIBLE=False),
    Bool32("render_only_section_flags_4", *("section_%s" % i for i in range(96, 128)), VISIBLE=False),
    Bool32("render_only_section_flags_5", *("section_%s" % i for i in range(128, 160)), VISIBLE=False),
    Bool32("render_only_section_flags_6", *("section_%s" % i for i in range(160, 192)), VISIBLE=False),
    Bool32("render_only_section_flags_7", *("section_%s" % i for i in range(192, 224)), VISIBLE=False),
    Bool32("render_only_section_flags_8", *("section_%s" % i for i in range(224, 256)), VISIBLE=False),
    Bool32("runtime_flags", 
        "contains_runtime_nodes",
        VISIBLE=False,
        ),
    BytesRaw("scenario_load_parameters_block", SIZE=12, VISIBLE=False),
    SInt16("unknown_1", VISIBLE=False),
    SInt16("unknown_2", VISIBLE=False),
    reflexive("unknown_3", hlmt_unknown_3),
    reflexive("unknown_4", hlmt_unknown_4),
    reflexive("unknown_5", hlmt_unknown_5),
    dependency("shield_impact_third_person"),
    dependency("shield_impact_first_person"),
    TYPE=Struct, ENDIAN=">", SIZE=392
    )