############# Credits and version info #############
# Definition autogenerated from Assembly XML tag def
#
# revision: 1		author: -DeToX-
# 	Mapped plugin structure a new.
# revision: 2		author: Moses_of_Egypt
# 	Cleaned up and converted to SuPyr definition
#
####################################################
from reclaimer.common_descs import *
from supyr_struct.defs.tag_def import TagDef


hlsl_meta_def = BlockDef("hlsl", 
    BytesRaw("unknown", SIZE=20, VISIBLE=False),
    TYPE=Struct, ENDIAN=">", SIZE=20
    )