############# Credits and version info #############
# Definition autogenerated from Assembly XML tag def
#
# revision: 1		author: Assembly
# 	Generated plugin from scratch.
# revision: 2		author: DeadCanadian
# 	named a few things
# revision: 3		author: Moses_of_Egypt
# 	Cleaned up and converted to SuPyr definition
#
####################################################
from reclaimer.common_descs import *
from supyr_struct.defs.tag_def import TagDef

jmrq_sandbox_text_value_pair_text_value_pair_expected_value_type = (
    "integer_index",
    "stringid_reference",
    "incremental",
    )


jmrq_sandbox_text_value_pair_text_value_pair = Struct("text_value_pair", 
    Bool8("flags", 
        "default",
        "unchanged",
        "_2",
        "_3",
        ),
    SEnum8("expected_value_type", *jmrq_sandbox_text_value_pair_text_value_pair_expected_value_type),
    SInt16("unknown", VISIBLE=False),
    SInt32("int_value"),
    string_id_meta("ref_name"),
    string_id_meta("name"),
    string_id_meta("description"),
    ENDIAN=">", SIZE=20
    )


jmrq_sandbox_text_value_pair = Struct("sandbox_text_value_pair", 
    string_id_meta("parameter_name"),
    reflexive("text_value_pairs", jmrq_sandbox_text_value_pair_text_value_pair),
    ENDIAN=">", SIZE=16
    )


jmrq_meta_def = BlockDef("jmrq", 
    reflexive("sandbox_text_value_pairs", jmrq_sandbox_text_value_pair),
    TYPE=Struct, ENDIAN=">", SIZE=12
    )