############# Credits and version info #############
# Definition autogenerated from Assembly XML tag def
#
# revision: 1		author: Assembly
# 	Generated plugin from scratch.
# revision: 2		author: Moses_of_Egypt
# 	Cleaned up and converted to SuPyr definition
#
####################################################
from reclaimer.common_descs import *
from supyr_struct.defs.tag_def import TagDef


nclt_unknown_0 = Struct("unknown_0", 
    SInt32("unknown_0", VISIBLE=False),
    BytesRaw("unknown_1", SIZE=28, VISIBLE=False),
    VISIBLE=False,
    ENDIAN=">", SIZE=32
    )


nclt_unknown_1 = Struct("unknown_1", 
    BytesRaw("unknown_0", SIZE=16, VISIBLE=False),
    dependency("unknown_1", VISIBLE=False),
    VISIBLE=False,
    ENDIAN=">", SIZE=32
    )


nclt_meta_def = BlockDef("nclt", 
    reflexive("unknown_0", nclt_unknown_0),
    reflexive("unknown_1", nclt_unknown_1),
    BytesRaw("unknown_2", SIZE=4, VISIBLE=False),
    TYPE=Struct, ENDIAN=">", SIZE=28
    )