############# Credits and version info #############
# Definition autogenerated from Assembly XML tag def
#
# revision: 1		author: Assembly
# 	Generated plugin from scratch.
# revision: 2		author: -DeToX-
# 	Mapped out most of the tag
# revision: 3		author: Moses_of_Egypt
# 	Cleaned up and converted to SuPyr definition
#
####################################################
from reclaimer.common_descs import *
from supyr_struct.defs.tag_def import TagDef


rasg_default_bitmap = Struct("default_bitmap", 
    SInt32("unknown", VISIBLE=False),
    dependency("bitmap"),
    ENDIAN=">", SIZE=20
    )


rasg_default_rasterizer_bitmap = Struct("default_rasterizer_bitmap", 
    dependency("bitmap"),
    ENDIAN=">", SIZE=16
    )


rasg_default_shader = Struct("default_shader", 
    dependency("vertex_shader"),
    dependency("pixel_shader"),
    ENDIAN=">", SIZE=32
    )


rasg_meta_def = BlockDef("rasg", 
    reflexive("default_bitmaps", rasg_default_bitmap),
    reflexive("default_rasterizer_bitmaps", rasg_default_rasterizer_bitmap),
    dependency("vertex_shader_simple"),
    dependency("pixel_shader_simple"),
    reflexive("default_shaders", rasg_default_shader),
    BytesRaw("unknown_0", SIZE=12, VISIBLE=False),
    SInt32("unknown_1", VISIBLE=False),
    SInt32("unknown_2", VISIBLE=False),
    dependency("active_camo_distortion"),
    dependency("default_performance_template"),
    dependency("default_shield_impact"),
    SInt32("unknown_3", VISIBLE=False),
    BytesRaw("unknown_4", SIZE=24, VISIBLE=False),
    TYPE=Struct, ENDIAN=">", SIZE=164
    )