############# Credits and version info #############
# Definition autogenerated from Assembly XML tag def
#
# revision: 1		author: Assembly
# 	Generated plugin from scratch.
# revision: 2		author: Moses_of_Egypt
# 	Cleaned up and converted to SuPyr definition
#
####################################################
from reclaimer.common_descs import *
from supyr_struct.defs.tag_def import TagDef


rmdf_method_shader_option = Struct("shader_option", 
    string_id_meta("type"),
    dependency("option"),
    string_id_meta("unknown_0", VISIBLE=False),
    string_id_meta("unknown_1", VISIBLE=False),
    ENDIAN=">", SIZE=28
    )


rmdf_method = Struct("method", 
    string_id_meta("type"),
    reflexive("shader_options", rmdf_method_shader_option),
    string_id_meta("unknown_0", VISIBLE=False),
    string_id_meta("unknown_1", VISIBLE=False),
    ENDIAN=">", SIZE=24
    )


rmdf_unknown_1_unknown_1_unknown_1 = Struct("unknown_1", 
    BytesRaw("unknown", SIZE=4, VISIBLE=False),
    VISIBLE=False,
    ENDIAN=">", SIZE=4
    )


rmdf_unknown_1_unknown_1 = Struct("unknown_1", 
    BytesRaw("unknown_0", SIZE=4, VISIBLE=False),
    reflexive("unknown_1", rmdf_unknown_1_unknown_1_unknown_1),
    VISIBLE=False,
    ENDIAN=">", SIZE=16
    )


rmdf_unknown_1 = Struct("unknown_1", 
    BytesRaw("unknown_0", SIZE=4, VISIBLE=False),
    reflexive("unknown_1", rmdf_unknown_1_unknown_1),
    VISIBLE=False,
    ENDIAN=">", SIZE=16
    )


rmdf_unknown_2 = Struct("unknown_2", 
    BytesRaw("unknown", SIZE=16, VISIBLE=False),
    VISIBLE=False,
    ENDIAN=">", SIZE=16
    )


rmdf_meta_def = BlockDef("rmdf", 
    dependency("unknown_0", VISIBLE=False),
    reflexive("methods", rmdf_method),
    reflexive("unknown_1", rmdf_unknown_1),
    reflexive("unknown_2", rmdf_unknown_2),
    dependency("unknown_3", VISIBLE=False),
    dependency("unknown_4", VISIBLE=False),
    BytesRaw("unknown_5", SIZE=8, VISIBLE=False),
    TYPE=Struct, ENDIAN=">", SIZE=92
    )