############# Credits and version info #############
# Definition autogenerated from Assembly XML tag def
#
# revision: 1		author: Assembly
# 	Generated plugin from scratch.
# revision: 2		author: Moses_of_Egypt
# 	Cleaned up and converted to SuPyr definition
#
####################################################
from reclaimer.common_descs import *
from supyr_struct.defs.tag_def import TagDef


rmop_unknown = Struct("unknown", 
    string_id_meta("type"),
    BytesRaw("unknown_0", SIZE=8, VISIBLE=False),
    dependency("unknown_1", VISIBLE=False),
    BytesRaw("unknown_2", SIZE=44, VISIBLE=False),
    VISIBLE=False,
    ENDIAN=">", SIZE=72
    )


rmop_meta_def = BlockDef("rmop", 
    reflexive("unknown", rmop_unknown),
    TYPE=Struct, ENDIAN=">", SIZE=12
    )