############# Credits and version info #############
# Definition autogenerated from Assembly XML tag def
#
# revision: 1		author: Assembly
# 	Generated plugin from scratch.
# revision: 2		author: Moses_of_Egypt
# 	Cleaned up and converted to SuPyr definition
#
####################################################
from reclaimer.common_descs import *
from supyr_struct.defs.tag_def import TagDef


rmt2_unknown_1 = Struct("unknown_1", 
    SInt16("unknown", VISIBLE=False),
    VISIBLE=False,
    ENDIAN=">", SIZE=2
    )


rmt2_unknown_2 = Struct("unknown_2", 
    BytesRaw("unknown", SIZE=28, VISIBLE=False),
    VISIBLE=False,
    ENDIAN=">", SIZE=28
    )


rmt2_unknown_3 = Struct("unknown_3", 
    BytesRaw("unknown", SIZE=4, VISIBLE=False),
    VISIBLE=False,
    ENDIAN=">", SIZE=4
    )


rmt2_argument = Struct("argument", 
    string_id_meta("name"),
    ENDIAN=">", SIZE=4
    )


rmt2_unknown_4 = Struct("unknown_4", 
    string_id_meta("unknown", VISIBLE=False),
    VISIBLE=False,
    ENDIAN=">", SIZE=4
    )


rmt2_unknown_5 = Struct("unknown_5", 
    string_id_meta("unknown", VISIBLE=False),
    VISIBLE=False,
    ENDIAN=">", SIZE=4
    )


rmt2_shader_map = Struct("shader_map", 
    string_id_meta("name"),
    ENDIAN=">", SIZE=4
    )


rmt2_meta_def = BlockDef("rmt2", 
    dependency("vertex_shader"),
    dependency("pixel_shader"),
    BytesRaw("unknown_0", SIZE=4, VISIBLE=False),
    reflexive("unknown_1", rmt2_unknown_1),
    reflexive("unknown_2", rmt2_unknown_2),
    reflexive("unknown_3", rmt2_unknown_3),
    reflexive("arguments", rmt2_argument),
    reflexive("unknown_4", rmt2_unknown_4),
    reflexive("unknown_5", rmt2_unknown_5),
    reflexive("shader_maps", rmt2_shader_map),
    BytesRaw("unknown_6", SIZE=12, VISIBLE=False),
    TYPE=Struct, ENDIAN=">", SIZE=132
    )