############# Credits and version info #############
# Definition autogenerated from Assembly XML tag def
#
# revision: 1		author: Assembly
# 	Generated plugin from scratch.
# revision: 2		author: Moses_of_Egypt
# 	Cleaned up and converted to SuPyr definition
#
####################################################
from reclaimer.common_descs import *
from supyr_struct.defs.tag_def import TagDef


sfx__sound_effect_filter = Struct("filter", 
    SInt32("filter_type"),
    SInt32("filter_width"),
    Pad(64),
    ENDIAN=">", SIZE=72
    )


sfx__sound_effect_pitch_lfo = Struct("pitch_lfo", 
    Pad(48),
    ENDIAN=">", SIZE=48
    )


sfx__sound_effect_filter_lfo = Struct("filter_lfo", 
    Pad(64),
    ENDIAN=">", SIZE=48
    )


sfx__sound_effect_sound_effect_component = Struct("component", 
    dependency("sound"),
    Pad(4),
    SInt32("flags"),
    ENDIAN=">", SIZE=24
    )


sfx__sound_effect_sound_effect_template_collection_parameter = Struct("parameter", 
    string_id_meta("name"),
    Pad(20),
    rawdata_ref("function"),
    ENDIAN=">", SIZE=44
    )


sfx__sound_effect_sound_effect_template_collection = Struct("template_collection", 
    string_id_meta("dsp_effect"),
    reflexive("parameters", sfx__sound_effect_sound_effect_template_collection_parameter),
    VISIBLE=False,
    ENDIAN=">", SIZE=16
    )


sfx__sound_effect_sound_effect = Struct("sound_effect", 
    dependency("unknown_0"),
    reflexive("components", sfx__sound_effect_sound_effect_component),
    reflexive("template_collection", sfx__sound_effect_sound_effect_template_collection),
    BytesRaw("unknown_1", SIZE=32, VISIBLE=False),
    ENDIAN=">", SIZE=72
    )


sfx__sound_effect = Struct("sound_effect", 
    string_id_meta("name"),
    BytesRaw("unknown_0", SIZE=12, VISIBLE=False),
    Bool32("flags", 
        "use_3d_radio_hack",
        ),
    BytesRaw("unknown_1", SIZE=8, VISIBLE=False),
    reflexive("filter", sfx__sound_effect_filter),
    reflexive("pitch_lfo", sfx__sound_effect_pitch_lfo),
    reflexive("filter_lfo", sfx__sound_effect_filter_lfo),
    reflexive("sound_effect", sfx__sound_effect_sound_effect),
    ENDIAN=">", SIZE=76
    )


sfx__meta_def = BlockDef("sfx_", 
    reflexive("sound_effects", sfx__sound_effect),
    TYPE=Struct, ENDIAN=">", SIZE=12
    )