############# Credits and version info #############
# Definition autogenerated from Assembly XML tag def
#
# revision: 1		author: Assembly
# 	Generated plugin from scratch.
# revision: 2		author: Lord Zedd
# 	Woo
# revision: 3		author: Moses_of_Egypt
# 	Cleaned up and converted to SuPyr definition
#
####################################################
from reclaimer.common_descs import *
from supyr_struct.defs.tag_def import TagDef


sgp__meta_def = BlockDef("sgp_", 
    dependency("underwater_environment"),
    dependency("underwater_loop"),
    BytesRaw("unknown", SIZE=8, VISIBLE=False),
    dependency("enter_underater"),
    dependency("exit_underwater"),
    TYPE=Struct, ENDIAN=">", SIZE=72
    )