############# Credits and version info #############
# Definition autogenerated from Assembly XML tag def
#
# revision: 1		author: Assembly
# 	Generated plugin from scratch.
# revision: 2		author: Moses_of_Egypt
# 	Cleaned up and converted to SuPyr definition
#
####################################################
from reclaimer.common_descs import *
from supyr_struct.defs.tag_def import TagDef


udlg_vocalization = Struct("vocalization", 
    Bool16("flags", 
        "new_vocalization",
        ),
    SInt16("unknown", VISIBLE=False),
    string_id_meta("vocalization"),
    dependency("sound"),
    ENDIAN=">", SIZE=24
    )


udlg_meta_def = BlockDef("udlg", 
    dependency("global_dialogue_info"),
    Bool32("flags", 
        "female",
        ),
    reflexive("vocalizations", udlg_vocalization),
    string_id_meta("mission_dialogue_designator"),
    TYPE=Struct, ENDIAN=">", SIZE=36
    )