from reclaimer.common_descs import *
from supyr_struct.defs.tag_def import TagDef

vehi_ai_propertie_leap_jump_speed = (
    "none",
    "down",
    "step",
    "crouch",
    "stand",
    "storey",
    "tower",
    "infinite",
    )

vehi_ai_propertie_size = (
    "default",
    "tiny",
    "small",
    "medium",
    "large",
    "huge",
    "immobile",
    )

vehi_attachment_change_color = (
    "none",
    "primary",
    "secondary",
    "tertiary",
    "quaternary",
    )

vehi_constant_sound_volume = (
    "silent",
    "medium",
    "loud",
    "shout",
    "quiet",
    )

vehi_default_team = (
    "default",
    "player",
    "human",
    "covenant",
    "flood",
    "sentinel",
    "heretic",
    "prophet",
    "guilty",
    "unused9",
    "unused10",
    "unused11",
    "unused12",
    "unused13",
    "unused14",
    "unused15",
    )

vehi_friction_point_friction_type = (
    "point",
    "forward",
    )

vehi_friction_point_model_state_destroyed = (
    "default",
    "minor_damage",
    "medium_damage",
    "major_damage",
    "destroyed",
    )

vehi_grenade_type = (
    "human_fragmentation",
    "covenant_plasma",
    "brute_spike",
    "firebomb",
    )

vehi_item_scale = (
    "small",
    "medium",
    "large",
    "huge",
    )

vehi_lightmap_shadow_mode_size = (
    "default",
    "never",
    "always",
    "unknown",
    )

vehi_metagame_propertie_classification = (
    "infantry",
    "leader",
    "hero",
    "specialist",
    "light_vehicle",
    "heavy_vehicle",
    "giant_vehicle",
    "standard_vehicle",
    )

vehi_metagame_propertie_unit = (
    "brute",
    "grunt",
    "jackal",
    "marine",
    "bugger",
    "hunter",
    "flood_infection",
    "flood_carrier",
    "flood_combat",
    "flood_pureform",
    "sentinel",
    "elite",
    "turret",
    "mongoose",
    "warthog",
    "scorpion",
    "hornet",
    "pelican",
    "shade",
    "watchtower",
    "ghost",
    "chopper",
    "mauler",
    "wraith",
    "banshee",
    "phantom",
    "scarab",
    "guntower",
    )

vehi_motion_sensor_blip_size = (
    "medium",
    "small",
    "large",
    )

vehi_multiplayer_object_propertie_object_type = (
    "ordinary",
    "weapon",
    "grenade",
    "projectile",
    "powerup",
    "equipment",
    "light_land_vehicle",
    "heavy_land_vehicle",
    "flying_vehicle",
    "teleporter_2way",
    "teleporter_sender",
    "teleporter_receiver",
    "player_spawn_location",
    "player_respawn_zone",
    "hold_spawn_objective",
    "capture_spawn_objective",
    "hold_destination_objective",
    "capture_destination_objective",
    "hill_objective",
    "infection_haven_objective",
    "territory_objective",
    "vip_boundary_objective",
    "vip_destination_objective",
    "juggernaut_destination_objective",
    )

vehi_multiplayer_object_propertie_shape = (
    "none",
    "sphere",
    "cylinder",
    "box",
    )

vehi_multiplayer_object_propertie_spawn_timer_mode = (
    "on_death",
    "on_disturbance",
    )

vehi_object_type = (
    "biped",
    "vehicle",
    "weapon",
    "equipment",
    "terminal",
    "projectile",
    "scenery",
    "machine",
    "control",
    "sound_scenery",
    "crate",
    "creature",
    "giant",
    "effect_scenery",
    )

vehi_player_training_vehicle_type = (
    "none",
    "warthog",
    "warthog_turret",
    "ghost",
    "banshee",
    "tank",
    "wraith",
    )

vehi_seat_ai_seat_type = (
    "none",
    "passenger",
    "gunner",
    "small_cargo",
    "large_cargo",
    "driver",
    )

vehi_sweetener_size = (
    "small",
    "medium",
    "large",
    )

vehi_vehicle_size = (
    "small",
    "large",
    )

vehi_water_density = (
    "default",
    "least",
    "some",
    "equal",
    "more",
    "more_still",
    "lots_more",
    )


vehi_early_mover_propertie = Struct("early_mover_properties",
    string_id_meta("name"),
    Pad(36),
    ENDIAN=">", SIZE=40
    )


vehi_ai_propertie = Struct("ai_properties",
    Bool32("flags",
        "destroyable_cover",
        "pathfinding_ignore_when_dead",
        "dynamic_cover",
        ),
    string_id_meta("ai_type_name"),
    Pad(4),
    SEnum16("size", *vehi_ai_propertie_size),
    SEnum16("leap_jump_speed", *vehi_ai_propertie_leap_jump_speed),
    ENDIAN=">", SIZE=16
    )


vehi_function = Struct("functions",
    Bool32("flags",
        "invert",
        "mapping_does_not_controls_active",
        "always_active",
        "random_time_offset",
        ),
    string_id_meta("import_name"),
    string_id_meta("export_name"),
    string_id_meta("turn_off_with"),
    Float("minimum_value"),
    rawdata_ref("default_function"),
    string_id_meta("scale_by"),
    ENDIAN=">", SIZE=44
    )


vehi_attachment = Struct("attachments",
    dependency("attachment"),
    string_id_meta("marker"),
    SEnum16("change_color", *vehi_attachment_change_color),
    SInt16("unknown"),
    string_id_meta("primary_scale"),
    string_id_meta("secondary_scale"),
    ENDIAN=">", SIZE=32
    )


vehi_widget = Struct("widgets",
    dependency("type"),
    ENDIAN=">", SIZE=16
    )


vehi_change_color_initial_permutation = Struct("initial_permutations",
    Pad(4),
    color_rgb_float("color_lower_bound"),
    color_rgb_float("color_upper_bound"),
    string_id_meta("variant_name"),
    ENDIAN=">", SIZE=32
    )


vehi_change_color_function = Struct("functions",
    Bool32("scale_flags",
        "blend_in_hsv",
        "more_colors",
        ),
    color_rgb_float("color_lower_bound"),
    color_rgb_float("color_upper_bound"),
    string_id_meta("darken_by"),
    string_id_meta("scale_by"),
    ENDIAN=">", SIZE=32
    )


vehi_change_color = Struct("change_colors",
    reflexive("initial_permutations", vehi_change_color_initial_permutation),
    reflexive("functions", vehi_change_color_function),
    ENDIAN=">", SIZE=24
    )


vehi_predicted_resource = Struct("predicted_resources",
    SInt16("type"),
    SInt16("resource_index"),
    UInt32("tag_index"),
    ENDIAN=">", SIZE=8
    )


vehi_multiplayer_object_propertie = Struct("multiplayer_object_properties",
    Bool16("engine_flags",
        "capture_the_flag",
        "slayer",
        "oddball",
        "king_of_the_hill",
        "juggernaut",
        "territories",
        "assault",
        "vip",
        "infection",
        ),
    SEnum8("object_type", *vehi_multiplayer_object_propertie_object_type),
    Bool8("teleporter_flags",
        "disallows_players",
        "allows_land_vehicles",
        "allows_heavy_vehicles",
        "allows_flying_vehicles",
        "allows_projectiles",
        ),
    Bool16("flags",
        "editor_only",
        ),
    SEnum8("shape", *vehi_multiplayer_object_propertie_shape),
    SEnum8("spawn_timer_mode", *vehi_multiplayer_object_propertie_spawn_timer_mode),
    SInt16("spawn_time"),
    SInt16("abandon_time"),
    Float("radius_width"),
    Float("length"),
    Float("top"),
    Float("bottom"),
    Float("unknown"),
    Float("unknown_1"),
    Float("unknown_2"),
    SInt32("unknown_3"),
    SInt32("unknown_4"),
    dependency("child_object"),
    SInt32("unknown_5"),
    dependency("shape_shader"),
    dependency("unknown_shader"),
    dependency("unknown_6"),
    dependency("unknown_7"),
    dependency("unknown_8"),
    dependency("unknown_9"),
    dependency("unknown_10"),
    dependency("unknown_11"),
    ENDIAN=">", SIZE=196
    )


vehi_metagame_propertie = Struct("metagame_properties",
    Bool8("flags",
        "must_have_active_seats",
        ),
    SEnum8("unit", *vehi_metagame_propertie_unit),
    SEnum8("classification", *vehi_metagame_propertie_classification),
    SInt8("unknown"),
    SInt16("points"),
    SInt16("unknown_1"),
    ENDIAN=">", SIZE=8
    )


vehi_camera_track = Struct("camera_tracks",
    dependency("track"),
    ENDIAN=">", SIZE=16
    )


vehi_unknown_7 = Struct("unknown_7",
    Float("unknown"),
    Float("unknown_1"),
    Float("unknown_2"),
    Float("unknown_3"),
    Float("unknown_4"),
    Float("unknown_5"),
    Float("unknown_6"),
    Float("unknown_7"),
    Float("unknown_8"),
    Float("unknown_9"),
    Float("unknown_10"),
    Float("unknown_11"),
    Float("unknown_12"),
    Float("unknown_13"),
    Float("unknown_14"),
    Float("unknown_15"),
    Float("unknown_16"),
    Float("unknown_17"),
    Float("unknown_18"),
    ENDIAN=">", SIZE=76
    )


vehi_posture = Struct("postures",
    string_id_meta("name"),
    Float("pill_offset_i"),
    Float("pill_offset_j"),
    Float("pill_offset_k"),
    ENDIAN=">", SIZE=16
    )


vehi_hud_interface = Struct("hud_interfaces",
    dependency("unit_hud_interface"),
    ENDIAN=">", SIZE=16
    )


vehi_dialogue_variant = Struct("dialogue_variants",
    SInt16("variant_number"),
    SInt16("unknown"),
    dependency("dialogue"),
    ENDIAN=">", SIZE=20
    )


vehi_powered_seat = Struct("powered_seats",
    Float("driver_powerup_time"),
    Float("driver_powerdown_time"),
    ENDIAN=">", SIZE=8
    )


vehi_weapon = Struct("weapons",
    dependency("weapon"),
    ENDIAN=">", SIZE=16
    )


vehi_seat_camera_track = Struct("camera_tracks",
    dependency("track"),
    ENDIAN=">", SIZE=16
    )


vehi_seat_unknown_6 = Struct("unknown_6",
    Float("unknown"),
    Float("unknown_1"),
    Float("unknown_2"),
    Float("unknown_3"),
    Float("unknown_4"),
    Float("unknown_5"),
    Float("unknown_6"),
    Float("unknown_7"),
    Float("unknown_8"),
    Float("unknown_9"),
    Float("unknown_10"),
    Float("unknown_11"),
    Float("unknown_12"),
    Float("unknown_13"),
    Float("unknown_14"),
    Float("unknown_15"),
    Float("unknown_16"),
    Float("unknown_17"),
    Float("unknown_18"),
    ENDIAN=">", SIZE=76
    )


vehi_seat_unit_hud_interface = Struct("unit_hud_interface",
    dependency("unit_hud_interface"),
    ENDIAN=">", SIZE=16
    )


vehi_seat = Struct("seats",
    Bool32("flags",
        "invisible",
        "locked",
        "driver",
        "gunner",
        "third_person_camera",
        "allows_weapons",
        "third_person_on_enter",
        "first_person_camera_slaved_to_gun",
        "allow_vehicle_communication_animations",
        "not_valid_without_driver",
        "allow_ai_noncombatants",
        "boarding_seat",
        "ai_firing_disabled_by_max_acceleration",
        "boarding_enters_seat",
        "boarding_need_any_passenger",
        "controls_open_and_close",
        "invalid_for_player",
        "invalid_for_non_player",
        "gunner_player_only",
        "invisible_under_major_damage",
        ("detachable_weapon", 1 << 22),
        ),
    string_id_meta("seat_animation"),
    string_id_meta("seat_marker_name"),
    string_id_meta("entry_marker_s_name"),
    string_id_meta("boarding_grenade_marker"),
    string_id_meta("boarding_grenade_string"),
    string_id_meta("boarding_melee_string"),
    string_id_meta("detach_weapon_string"),
    Float("ping_scale"),
    Float("turnover_time"),
    Float("acceleration_range_i"),
    Float("acceleration_range_j"),
    Float("acceleration_range_k"),
    Float("acceleration_action_scale"),
    Float("acceleration_attach_scale"),
    Float("ai_scariness"),
    SEnum16("ai_seat_type", *vehi_seat_ai_seat_type),
    SInt16("boarding_seat"),
    Float("listener_interpolation_factor"),
    Float("yaw_rate_bounds_min"),
    Float("yaw_rate_bounds_max"),
    Float("pitch_rate_bounds_min"),
    Float("pitch_rate_bounds_max"),
    Float("unknown"),
    Float("minimum_speed_reference"),
    Float("maximum_speed_reference"),
    Float("speed_exponent"),
    SInt16("unknown_1"),
    SInt16("unknown_2"),
    string_id_meta("camera_marker_name"),
    string_id_meta("camera_submerged_marker_name"),
    float_rad("pitch_auto_level"),
    float_rad("pitch_range_min"),
    float_rad("pitch_range_max"),
    reflexive("camera_tracks", vehi_seat_camera_track),
    float_rad("unknown_3"),
    float_rad("unknown_4"),
    float_rad("unknown_5"),
    reflexive("unknown_6", vehi_seat_unknown_6),
    reflexive("unit_hud_interface", vehi_seat_unit_hud_interface),
    string_id_meta("enter_seat_string"),
    float_rad("yaw_range_min"),
    float_rad("yaw_range_max"),
    dependency("built_in_gunner"),
    Float("entry_radius"),
    float_rad("entry_marker_cone_angle"),
    float_rad("entry_marker_facing_angle"),
    Float("maximum_relative_velocity"),
    string_id_meta("invisible_seat_region"),
    SInt32("runtime_invisible_seat_region_index"),
    ENDIAN=">", SIZE=228
    )


vehi_tank_engine_motion_propertie_gear = Struct("gears",
    Float("min_torque"),
    Float("max_torque"),
    Float("peak_torque_scale"),
    Float("past_peak_torque_exponent"),
    Float("torque_at_max_angular_velovity"),
    Float("torque_at_2x_max_angular_velocity"),
    Float("min_torque_1"),
    Float("max_torque_1"),
    Float("peak_torque_scale_1"),
    Float("past_peak_torque_exponent_1"),
    Float("torque_at_max_angular_velovity_1"),
    Float("torque_at_2x_max_angular_velocity_1"),
    Float("min_time_to_upshift"),
    Float("engine_upshift_scale"),
    Float("gear_ratio"),
    Float("min_time_to_downshift"),
    Float("engine_downshift_scale"),
    ENDIAN=">", SIZE=68
    )


vehi_tank_engine_motion_propertie = Struct("tank_engine_motion_properties",
    float_rad("steering_overdampen_cusp_angle"),
    Float("steering_overdamen_exponent"),
    Float("unknown"),
    Float("speed_left"),
    Float("speed_right"),
    Float("turning_speed_left"),
    Float("turning_speed_right"),
    Float("speed_left_2"),
    Float("speed_right_2"),
    Float("turning_speed_left_2"),
    Float("turning_speed_right_2"),
    Float("engine_momentum"),
    Float("engine_maximum_angular_velocity"),
    reflexive("gears", vehi_tank_engine_motion_propertie_gear),
    dependency("change_gear_sound"),
    Float("unknown_1"),
    Float("unknown_2"),
    ENDIAN=">", SIZE=88
    )


vehi_engine_motion_propertie_gear = Struct("gears",
    Float("min_torque"),
    Float("max_torque"),
    Float("peak_torque_scale"),
    Float("past_peak_torque_exponent"),
    Float("torque_at_max_angular_velovity"),
    Float("torque_at_2x_max_angular_velocity"),
    Float("min_torque_1"),
    Float("max_torque_1"),
    Float("peak_torque_scale_1"),
    Float("past_peak_torque_exponent_1"),
    Float("torque_at_max_angular_velovity_1"),
    Float("torque_at_2x_max_angular_velocity_1"),
    Float("min_time_to_upshift"),
    Float("engine_upshift_scale"),
    Float("gear_ratio"),
    Float("min_time_to_downshift"),
    Float("engine_downshift_scale"),
    ENDIAN=">", SIZE=68
    )


vehi_engine_motion_propertie = Struct("engine_motion_properties",
    float_rad("steering_overdampen_cusp_angle"),
    Float("steering_overdamen_exponent"),
    float_rad("maximum_left_turn"),
    float_rad("maximum_right_turn_negative"),
    float_rad("turn_rate"),
    Float("engine_momentum"),
    Float("engine_maximum_angular_velocity"),
    reflexive("gears", vehi_engine_motion_propertie_gear),
    dependency("change_gear_sound"),
    Float("unknown"),
    Float("unknown_1"),
    ENDIAN=">", SIZE=64
    )


vehi_dropship_motion_propertie = Struct("dropship_motion_properties",
    Float("forward_acceleration"),
    Float("backward_acceleration"),
    Float("unknown"),
    Float("unknown_1"),
    Float("left_strafe_acceleration"),
    Float("right_strafe_acceleration"),
    Float("unknown_2"),
    Float("unknown_3"),
    Float("lift_acceleration"),
    Float("drop_acceleration"),
    Float("unknown_4"),
    Float("unknown_5"),
    Float("unknown_6"),
    Float("unknown_7"),
    Float("unknown_8"),
    Float("unknown_9"),
    float_rad("unknown_10"),
    Float("unknown_11"),
    float_rad("unknown_12"),
    ENDIAN=">", SIZE=76
    )


vehi_antigravity_motion_propertie = Struct("antigravity_motion_properties",
    float_rad("steering_overdampen_cusp_angle"),
    Float("steering_overdamen_exponent"),
    Float("maximum_forward_speed"),
    Float("maximum_reverse_speed"),
    Float("speed_acceleration"),
    Float("speed_deceleration"),
    Float("maximum_left_slide"),
    Float("maximum_right_slide"),
    Float("slide_acceleration"),
    Float("slide_deceleration"),
    SInt8("unknown"),
    SInt8("unknown_1"),
    SInt8("unknown_2"),
    SInt8("unknown_3"),
    Float("traction"),
    Pad(4),
    Float("turning_rate"),
    string_id_meta("unknown_5"),
    Float("unknown_6"),
    Float("unknown_7"),
    Float("unknown_8"),
    Float("unknown_9"),
    string_id_meta("unknown_10"),
    Float("unknown_11"),
    Float("unknown_12"),
    Float("unknown_13"),
    Float("unknown_14"),
    Float("unknown_15"),
    Float("unknown_16"),
    Float("unknown_17"),
    float_rad("unknown_18"),
    ENDIAN=">", SIZE=112
    )


vehi_jet_engine_motion_propertie = Struct("jet_engine_motion_properties",
    float_rad("steering_overdampen_cusp_angle"),
    Float("steering_overdamen_exponent"),
    float_rad("maximum_left_turn"),
    float_rad("maximum_right_turn_negative"),
    float_rad("turn_rate"),
    Float("flying_speed"),
    Float("acceleration"),
    Float("speed_acceleration"),
    Float("speed_deceleration"),
    Float("pitch_left_speed"),
    Float("pitch_right_speed"),
    Float("pitch_rate"),
    Float("unpitch_rate"),
    Float("flight_stability"),
    Pad(4),
    Float("nose_angle"),
    Float("unknown_1"),
    Float("unknown_2"),
    Float("unknown_3"),
    Float("falling_speed"),
    Float("falling_speed_2"),
    Float("unknown_4"),
    Float("unknown_5"),
    Float("idle_rise"),
    Float("idle_forward"),
    ENDIAN=">", SIZE=100
    )


vehi_turret_propertie = Struct("turret_properties",
    Pad(4),
    ENDIAN=">", SIZE=4
    )


vehi_helicopter_motion_propertie = Struct("helicopter_motion_properties",
    float_rad("maximum_left_turn"),
    float_rad("maximum_right_turn_negative"),
    float_rad("unknown"),
    string_id_meta("thrust_front_left"),
    string_id_meta("thrust_front_right"),
    string_id_meta("thrust"),
    float_rad("unknown_1"),
    float_rad("unknown_2"),
    float_rad("unknown_3"),
    float_rad("unknown_4"),
    Float("unknown_5"),
    Float("unknown_6"),
    Float("unknown_7"),
    Float("unknown_8"),
    Float("unknown_9"),
    Float("unknown_10"),
    Float("unknown_11"),
    Float("unknown_12"),
    Float("unknown_13"),
    Float("unknown_14"),
    Float("unknown_15"),
    Float("unknown_16"),
    Float("unknown_17"),
    Float("unknown_18"),
    Float("unknown_19"),
    float_rad("unknown_20"),
    float_rad("unknown_21"),
    Float("unknown_22"),
    Float("unknown_23"),
    ENDIAN=">", SIZE=116
    )


vehi_antigravity_engine_motion_propertie_gear = Struct("gears",
    Float("min_torque"),
    Float("max_torque"),
    Float("peak_torque_scale"),
    Float("past_peak_torque_exponent"),
    Float("torque_at_max_angular_velovity"),
    Float("torque_at_2x_max_angular_velocity"),
    Float("min_torque_1"),
    Float("max_torque_1"),
    Float("peak_torque_scale_1"),
    Float("past_peak_torque_exponent_1"),
    Float("torque_at_max_angular_velovity_1"),
    Float("torque_at_2x_max_angular_velocity_1"),
    Float("min_time_to_upshift"),
    Float("engine_upshift_scale"),
    Float("gear_ratio"),
    Float("min_time_to_downshift"),
    Float("engine_downshift_scale"),
    ENDIAN=">", SIZE=68
    )


vehi_antigravity_engine_motion_propertie = Struct("antigravity_engine_motion_properties",
    float_rad("steering_overdampen_cusp_angle"),
    Float("steering_overdamen_exponent"),
    float_rad("maximum_left_turn"),
    float_rad("maximum_right_turn_negative"),
    float_rad("turn_rate"),
    Float("engine_momentum"),
    Float("engine_maximum_angular_velocity"),
    reflexive("gears", vehi_antigravity_engine_motion_propertie_gear),
    dependency("change_gear_sound"),
    Float("unknown"),
    string_id_meta("unknown_1"),
    Float("unknown_2"),
    Float("unknown_3"),
    Float("unknown_4"),
    Float("unknown_5"),
    Float("unknown_6"),
    Float("unknown_7"),
    float_rad("unknown_8"),
    Float("unknown_9"),
    Float("unknown_10"),
    Float("unknown_11"),
    Float("unknown_12"),
    Float("unknown_13"),
    ENDIAN=">", SIZE=112
    )


vehi_autoturret_equipment = Struct("autoturret_equipment",
    float_rad("unknown"),
    Float("unknown_1"),
    Pad(12),
    Float("unknown_3"),
    Pad(12),
    Float("unknown_5"),
    Float("unknown_6"),
    Float("unknown_7"),
    ENDIAN=">", SIZE=48
    )


vehi_anti_gravity_point = Struct("anti_gravity_points",
    string_id_meta("marker_name"),
    Bool32("flags",
        "gets_damage_from_region",
        ),
    Float("antigrav_strength"),
    Float("antigrav_offset"),
    Float("antigrav_height"),
    Float("antigrav_dump_factor"),
    Float("antigrav_normal_k1"),
    Float("antigrav_normal_k0"),
    Float("radius"),
    Pad(12),
    SInt16("unknown_1"),
    SInt16("damage_source_region_index"),
    string_id_meta("damage_source_region_name"),
    Float("default_state_error"),
    Float("minor_damage_error"),
    Float("medium_damage_error"),
    Float("major_damage_error"),
    Float("destroyed_state_error"),
    ENDIAN=">", SIZE=76
    )


vehi_friction_point = Struct("friction_points",
    string_id_meta("marker_name"),
    Bool32("flags",
        "gets_damage_from_region",
        "powered",
        "front_turning",
        "rear_turning",
        "attached_to_e_brake",
        "can_be_destroyed",
        ),
    Float("fraction_of_total_mass"),
    Float("radius"),
    Float("damaged_radius"),
    SEnum16("friction_type", *vehi_friction_point_friction_type),
    SInt16("unknown"),
    Float("moving_friction_velocity_diff"),
    Float("e_brake_moving_friction"),
    Float("e_brake_friction"),
    Float("e_brake_moving_friction_velocity_diff"),
    Pad(20),
    string_id_meta("collision_material_name"),
    SInt16("collision_global_material_index"),
    SEnum16("model_state_destroyed", *vehi_friction_point_model_state_destroyed),
    string_id_meta("region_name"),
    SInt32("region_index"),
    ENDIAN=">", SIZE=76
    )


vehi_phantom_shape = Struct("phantom_shapes",
    SInt32("unknown"),
    SInt16("size"),
    SInt16("size_1"),
    SInt32("overall_shape_index"),
    SInt32("offset"),
    Pad(12),
    SInt32("unknown_2"),
    Pad(16),
    Float("unknown_4"),
    Float("unknown_5"),
    Float("unknown_6"),
    Float("unknown_7"),
    Float("unknown_8"),
    Float("unknown_9"),
    Float("unknown_10"),
    Pad(4),
    SInt32("multisphere_count"),
    Bool32("flags",
        "has_aabb_phantom",
        ),
    Float("x0"),
    Float("x1"),
    Float("y0"),
    Float("y1"),
    Float("z0"),
    Float("z1"),
    SInt32("unknown_12"),
    SInt16("size_2"),
    SInt16("size_3"),
    SInt32("overall_shape_index_1"),
    SInt32("offset_1"),
    SInt32("number_of_spheres"),
    Pad(140),
    SInt32("unknown_14"),
    SInt16("size_4"),
    SInt16("size_5"),
    SInt32("overall_shape_index_2"),
    SInt32("offset_2"),
    SInt32("number_of_spheres_1"),
    Pad(140),
    SInt32("unknown_16"),
    SInt16("size_6"),
    SInt16("size_7"),
    SInt32("overall_shape_index_3"),
    SInt32("offset_3"),
    SInt32("number_of_spheres_2"),
    Pad(140),
    SInt32("unknown_18"),
    SInt16("size_8"),
    SInt16("size_9"),
    SInt32("overall_shape_index_4"),
    SInt32("offset_4"),
    SInt32("number_of_spheres_3"),
    Pad(204),
    ENDIAN=">", SIZE=816
    )


vehi_meta_def = BlockDef("vehi",
    SEnum16("object_type", *vehi_object_type),
    Bool16("flags",
        "does_not_cast_shadow",
        "search_cardinal_direction_lightmaps",
        ("not_a_pathfinding_obstacle", 1 << 3),
        "extension_of_parent",
        "does_not_cause_collision_damage",
        "early_mover",
        "early_mover_localized_physics",
        "use_static_massive_lightmap_sample",
        "object_scales_attachments",
        "inherits_player_s_appearance",
        "dead_bipeds_can_t_localize",
        "attach_to_clusters_by_dynamic_sphere",
        "effects_created_by_this_object_do_not_spawn_objects_in_multiplayer",
        ),
    Float("bounding_radius"),
    Float("bounding_offset_x"),
    Float("bounding_offset_y"),
    Float("bounding_offset_z"),
    Float("acceleration_scale"),
    SEnum16("lightmap_shadow_mode_size", *vehi_lightmap_shadow_mode_size),
    SEnum8("sweetener_size", *vehi_sweetener_size),
    SEnum8("water_density", *vehi_water_density),
    SInt32("unknown"),
    Float("dynamic_light_sphere_radius"),
    Float("dynamic_light_sphere_offset_x"),
    Float("dynamic_light_sphere_offset_y"),
    Float("dynamic_light_sphere_offset_z"),
    string_id_meta("default_model_variant"),
    dependency("model"),
    dependency("crate_object"),
    dependency("collision_damage"),
    reflexive("early_mover_properties", vehi_early_mover_propertie),
    dependency("creation_effect"),
    dependency("material_effects"),
    dependency("melee_impact"),
    reflexive("ai_properties", vehi_ai_propertie),
    reflexive("functions", vehi_function),
    SInt16("hud_text_message_index"),
    SInt16("unknown_1"),
    reflexive("attachments", vehi_attachment),
    reflexive("widgets", vehi_widget),
    reflexive("change_colors", vehi_change_color),
    reflexive("predicted_resources", vehi_predicted_resource),
    reflexive("multiplayer_object_properties", vehi_multiplayer_object_propertie),
    Bool32("flags_1",
        "circular_aiming",
        "destroyed_after_dying",
        "half_speed_interpolation",
        "fires_from_camera",
        "entrance_inside_bounding_sphere",
        "doesn_t_show_readied_weapon",
        "causes_passenger_dialogue",
        "resists_pings",
        "melee_attack_is_fatal",
        "don_t_reface_during_pings",
        "has_no_aiming",
        "simple_creature",
        "impact_melee_attaches_to_unit",
        "impact_melee_dies_on_shield",
        "cannot_open_doors_automatically",
        "melee_attackers_cannot_attach",
        "not_instantly_killed_by_melee",
        "shield_sapping",
        "runs_around_flaming",
        "inconsequential",
        "special_cinematic_unit",
        "ignored_by_autoaiming",
        "shields_fry_infection_forms",
        "can_dual_wield",
        ("acts_as_gunner_for_parent", 1 << 25),
        "controlled_by_parent_gunner",
        "parent_s_primary_weapon",
        "unit_has_boost",
        ),
    SEnum16("default_team", *vehi_default_team),
    SEnum16("constant_sound_volume", *vehi_constant_sound_volume),
    reflexive("metagame_properties", vehi_metagame_propertie),
    dependency("integrated_light_toggle"),
    float_rad("camera_field_of_view"),
    Float("camera_stiffness"),
    SInt16("unknown_2"),
    SInt16("unknown_3"),
    string_id_meta("camera_marker_name"),
    string_id_meta("camera_submerged_marker_name"),
    float_rad("pitch_auto_level"),
    float_rad("pitch_range_min"),
    float_rad("pitch_range_max"),
    reflexive("camera_tracks", vehi_camera_track),
    float_rad("unknown_4"),
    float_rad("unknown_5"),
    float_rad("unknown_6"),
    reflexive("unknown_7", vehi_unknown_7),
    Float("acceleration_range_i"),
    Float("acceleration_range_j"),
    Float("acceleration_range_k"),
    Float("acceleration_action_scale"),
    Float("acceleration_attach_scale"),
    Float("soft_ping_threshold"),
    Float("soft_ping_interrupt_time"),
    Float("hard_ping_threshold"),
    Float("hard_ping_interrupt_time"),
    Float("feign_death_threshold"),
    Float("feign_death_time"),
    Float("distance_of_evade_animation"),
    Float("distance_of_dive_animation"),
    Float("stunned_movement_threshold"),
    Float("feign_death_chance"),
    Float("feign_repeat_chance"),
    dependency("spawned_turret_character"),
    SInt16("spawned_actor_count_min"),
    SInt16("spawned_actor_count_max"),
    Float("spawned_velocity"),
    float_rad("aiming_velocity_maximum"),
    float_rad("aiming_acceleration_maximum"),
    Float("casual_aiming_modifier"),
    float_rad("looking_velocity_maximum"),
    float_rad("looking_acceleration_maximum"),
    string_id_meta("right_hand_node"),
    string_id_meta("left_hand_node"),
    string_id_meta("preferred_gun_node"),
    dependency("melee_damage"),
    dependency("boarding_melee_damage"),
    dependency("boarding_melee_response"),
    dependency("ejection_melee_damage"),
    dependency("ejection_melee_response"),
    dependency("landing_melee_damage"),
    dependency("flurry_melee_damage"),
    dependency("obstacle_smash_damage"),
    SEnum16("motion_sensor_blip_size", *vehi_motion_sensor_blip_size),
    SEnum16("item_scale", *vehi_item_scale),
    reflexive("postures", vehi_posture),
    reflexive("hud_interfaces", vehi_hud_interface),
    reflexive("dialogue_variants", vehi_dialogue_variant),
    Float("grenade_velocity"),
    SEnum16("grenade_type", *vehi_grenade_type),
    SInt16("grenade_count"),
    reflexive("powered_seats", vehi_powered_seat),
    reflexive("weapons", vehi_weapon),
    reflexive("seats", vehi_seat),
    Float("emp_radius"),
    dependency("emp_effect"),
    dependency("boost_collision_damage"),
    Float("boost_peak_power"),
    Float("boost_rise_power"),
    Float("boost_peak_time"),
    Float("boost_fall_power"),
    Float("boost_dead_time"),
    Float("lipsync_attack_weight"),
    Float("lipsync_decay_weight"),
    dependency("detach_damage"),
    dependency("detached_weapon"),
    Bool32("flags_2",
        "no_friction_with_driver",
        "can_trigger_automatic_opening_doors",
        "autoaim_when_teamless",
        "ai_weapon_cannot_rotate",
        "ai_does_not_require_driver",
        "ai_driver_enable",
        "ai_driver_flying",
        "ai_driver_can_sidestep",
        "ai_driver_hovering",
        "noncombat_vehicle",
        "vehicle_is_child",
        "bounces_at_death_barriers",
        "hydraulics",
        ),
    reflexive("tank_engine_motion_properties", vehi_tank_engine_motion_propertie),
    reflexive("engine_motion_properties", vehi_engine_motion_propertie),
    reflexive("dropship_motion_properties", vehi_dropship_motion_propertie),
    reflexive("antigravity_motion_properties", vehi_antigravity_motion_propertie),
    reflexive("jet_engine_motion_properties", vehi_jet_engine_motion_propertie),
    reflexive("turret_properties", vehi_turret_propertie),
    Pad(12),
    reflexive("helicopter_motion_properties", vehi_helicopter_motion_propertie),
    reflexive("antigravity_engine_motion_properties", vehi_antigravity_engine_motion_propertie),
    reflexive("autoturret_equipment", vehi_autoturret_equipment),
    Bool32("flags_3",
        ),
    Float("ground_friction"),
    Float("ground_depth"),
    Float("ground_damp_factor"),
    Float("ground_moving_friction"),
    Float("ground_maximum_slope_0"),
    Float("ground_maximum_slope_1_less_than_slope_0"),
    Float("unknown_9"),
    Float("anti_gravity_bank_lift"),
    Float("steering_bank_reaction_scale"),
    Float("gravity_scale"),
    Float("radius"),
    Float("unknown_10"),
    Float("unknown_11"),
    Float("unknown_12"),
    reflexive("anti_gravity_points", vehi_anti_gravity_point),
    reflexive("friction_points", vehi_friction_point),
    reflexive("phantom_shapes", vehi_phantom_shape),
    SEnum8("player_training_vehicle_type", *vehi_player_training_vehicle_type),
    SEnum8("vehicle_size", *vehi_vehicle_size),
    SInt8("unknown_13"),
    SInt8("unknown_14"),
    Float("minimum_flipping_angular_velocity"),
    Float("maximum_flipping_angular_velocity"),
    Pad(8),
    Float("seat_entrance_acceleration_scale"),
    Float("seat_exit_acceleration_scale"),
    Float("flip_time"),
    string_id_meta("flip_over_message"),
    dependency("suspension_sound"),
    dependency("running_effect"),
    dependency("unknown_response"),
    dependency("unknown_response_1"),
    TYPE=Struct, ENDIAN=">", SIZE=1100
    )