############# Credits and version info #############
# Definition autogenerated from Assembly XML tag def
#
# revision: 1		author: Assembly
# 	Generated plugin from scratch.
# revision: 2		author: Moses_of_Egypt
# 	Cleaned up and converted to SuPyr definition
#
####################################################
from reclaimer.common_descs import *
from supyr_struct.defs.tag_def import TagDef


wacd_meta_def = BlockDef("wacd", 
    dependency("focus"),
    dependency("unfocus"),
    dependency("unknown_0"),
    dependency("unknown_1"),
    dependency("unknown_2"),
    dependency("unknown_3"),
    dependency("out"),
    dependency("in"),
    dependency("unknown_4"),
    dependency("unknown_5"),
    dependency("unknown_6"),
    dependency("unknown_7"),
    dependency("unknown_8"),
    dependency("unknown_9"),
    dependency("unknown_10"),
    dependency("unknown_11"),
    dependency("focus_in"),
    dependency("focus_out"),
    dependency("unknown_12"),
    dependency("unknown_13"),
    dependency("unknown_14"),
    dependency("unknown_15"),
    dependency("unknown_16"),
    dependency("unknown_17"),
    dependency("unknown_18"),
    dependency("unknown_19"),
    dependency("unknown_20"),
    dependency("unknown_21"),
    dependency("unknown_22"),
    dependency("unknown_23"),
    dependency("unknown_24"),
    dependency("unknown_25"),
    dependency("unknown_26"),
    dependency("unknown_27"),
    dependency("unknown_28"),
    dependency("unknown_29"),
    TYPE=Struct, ENDIAN=">", SIZE=576
    )