############# Credits and version info #############
# Definition autogenerated from Assembly XML tag def
#
# revision: 1		author: Lord Zedd
# 	I wanted to see what it did, sue me. Basically done.
# revision: 2		author: Moses_of_Egypt
# 	Cleaned up and converted to SuPyr definition
#
####################################################
from reclaimer.common_descs import *
from supyr_struct.defs.tag_def import TagDef


wfon_animation_definition = Struct("animation_definition", 
    UInt32("frame"),
    SInt16("font_index"),
    SInt16("unknown_0", VISIBLE=False),
    BytesRaw("unknown_1", SIZE=12, VISIBLE=False),
    ENDIAN=">", SIZE=20
    )


wfon_meta_def = BlockDef("wfon", 
    Bool32("animation_flags", 
        "loops",
        ),
    reflexive("animation_definition", wfon_animation_definition),
    rawdata_ref("data"),
    TYPE=Struct, ENDIAN=">", SIZE=36
    )