############# Credits and version info #############
# Definition autogenerated from Assembly XML tag def
#
# revision: 1		author: Assembly
# 	Generated plugin from scratch.
# revision: 2		author: DarkShallFall
# 	Labeled about 40 values, structures, and idents.
# revision: 3		author: -DeToX- and DarkShallFall
# 	Labelled reflexives and found their purposes, aswell as the service tag bipd strings.
# revision: 4		author: Lord Zedd
# 	Got most things
# revision: 5		author: Moses_of_Egypt
# 	Cleaned up and converted to SuPyr definition
#
####################################################
from reclaimer.common_descs import *
from supyr_struct.defs.tag_def import TagDef

unknown_flags_8 = tuple("bit_%s" % i for i in range(8))

wigl_alert_icon = (
    "none",
    "download",
    "pause",
    "upload",
    "checkbox",
    )

wigl_dialog_default_option = (
    "option_1",
    "option_2",
    "option_3",
    "option_4",
    )


wigl_text_color = Struct("text_color", 
    string_id_meta("name"),
    color_argb_float("color"),
    ENDIAN=">", SIZE=20
    )


wigl_player_color_player_text_color = Struct("player_text_color", 
    color_argb_float("color"),
    ENDIAN=">", SIZE=16
    )


wigl_player_color_team_text_color = Struct("team_text_color", 
    color_argb_float("color"),
    ENDIAN=">", SIZE=16
    )


wigl_player_color_player_ui_color = Struct("player_ui_color", 
    color_argb_float("color"),
    ENDIAN=">", SIZE=16
    )


wigl_player_color_team_ui_color = Struct("team_ui_color", 
    color_argb_float("color"),
    ENDIAN=">", SIZE=16
    )


wigl_player_color = Struct("player_color", 
    reflexive("player_text_color", wigl_player_color_player_text_color),
    reflexive("team_text_color", wigl_player_color_team_text_color),
    reflexive("player_ui_color", wigl_player_color_player_ui_color),
    reflexive("team_ui_color", wigl_player_color_team_ui_color),
    ENDIAN=">", SIZE=48
    )


wigl_alert = Struct("alert", 
    string_id_meta("name"),
    Bool8("flags", *unknown_flags_8),
    SInt8("unknown_0"),
    SEnum8("icon", *wigl_alert_icon),
    SInt8("unknown_1", VISIBLE=False),
    string_id_meta("title"),
    string_id_meta("body"),
    ENDIAN=">", SIZE=16
    )


wigl_dialog = Struct("dialog", 
    string_id_meta("name"),
    SInt16("unknown_0"),
    SInt16("unknown_1", VISIBLE=False),
    string_id_meta("title"),
    string_id_meta("body"),
    Array("option_array", SUB_STRUCT=string_id_meta("option"), SIZE=4),
    string_id_meta("key_legend"),
    SEnum16("default_option", *wigl_dialog_default_option),
    SInt16("unknown_2", VISIBLE=False),
    ENDIAN=">", SIZE=40
    )


wigl_global_data_source = Struct("global_data_source", 
    dependency("data_source"),
    ENDIAN=">", SIZE=16
    )


wigl_meta_def = BlockDef("wigl", 
    SInt16("inc_text_update_period"),
    SInt16("inc_text_block_character"),
    Float("near_clip_plane_distance"),
    Float("projection_plane_distance"),
    Float("far_clip_plane_distance"),
    dependency("global_strings"),
    dependency("damage_type_strings"),
    dependency("main_menu_music"),
    SInt32("music_fade_time"),
    color_argb_float("color"),
    color_argb_float("text_stroke_color"),
    reflexive("text_colors", wigl_text_color),
    reflexive("player_colors", wigl_player_color),
    dependency("ui_sounds"),
    reflexive("alerts", wigl_alert),
    reflexive("dialogs", wigl_dialog),
    reflexive("global_data_sources", wigl_global_data_source),
    QStruct("widescreen_bitmap_scale", INCLUDE=xy_float),
    QStruct("standard_bitmap_scale", INCLUDE=xy_float),
    QStruct("menu_blur", INCLUDE=xy_float),
    ascii_str32("ui_spartan_biped_name"),
    ascii_str32("ui_spartan_ai_squad_name"),
    string_id_meta("ui_spartan_ai_location_name"),
    ascii_str32("ui_elite_biped_name"),
    ascii_str32("ui_elite_ai_squad_name"),
    string_id_meta("ui_elite_ai_location_name"),
    SInt32("single_scroll_speed"),
    SInt32("scroll_speed_transition_wait_time"),
    SInt32("held_scroll_speed"),
    SInt32("attract_video_idle_wait"),
    TYPE=Struct, ENDIAN=">", SIZE=352
    )